// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the AdminPortal API.
public struct AdminPortal: Sendable {
    let transport: Transport

    /// Generate a Portal Link
    ///
    /// Generate a Portal Link scoped to an Organization.
    ///
    /// - Parameter organization: An [Organization](https://workos.com/docs/reference/organization) identifier.
    /// - Parameter returnUrl: The URL to go to when an admin clicks on your logo in the Admin Portal. If not specified, the return URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
    /// - Parameter successUrl: The URL to redirect the admin to when they finish setup. If not specified, the success URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
    /// - Parameter intent: The intent of the Admin Portal.
    /// - Parameter itContactEmails: The email addresses of the IT contacts to grant access to the Admin Portal for the given organization. Accepts up to 20 emails.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func generateLink(
        organization: String,
        returnUrl: String? = nil,
        successUrl: String? = nil,
        intent: GenerateLinkIntent? = nil,
        itContactEmails: [String]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> PortalLinkResponse {
        let path = "portal/generate_link"
        var body = EncodableBody()
        body.set("return_url", returnUrl)
        body.set("success_url", successUrl)
        body.set("organization", organization)
        body.set("intent", intent)
        body.set("it_contact_emails", itContactEmails)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: PortalLinkResponse.self
        )
    }
}
