// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the AuditLogs API.
public struct AuditLogs: Sendable {
    let transport: Transport

    init(transport: Transport) {
        self.transport = transport
    }

    /// Get Retention
    /// 
    /// Get the configured event retention period for the given Organization.
    public func getOrganizationAuditLogsRetention(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogsRetention {
        let path = "organizations/\(PathEncoding.segment(id))/audit_logs_retention"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: AuditLogsRetention.self
        )
    }

    /// Set Retention
    /// 
    /// Set the event retention period for the given Organization.
    public func updateOrganizationAuditLogsRetention(
        id: String,
        retentionPeriodInDays: Int,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogsRetention {
        let path = "organizations/\(PathEncoding.segment(id))/audit_logs_retention"
        var body = EncodableBody()
        body.set("retention_period_in_days", retentionPeriodInDays)
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuditLogsRetention.self
        )
    }

    /// List Actions
    /// 
    /// Get a list of all Audit Log actions in the current environment.
    public func listActions(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<AuditLogAction> {
        let path = "audit_logs/actions"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<AuditLogAction>.self
        )
    }

    /// List Schemas
    /// 
    /// Get a list of all schemas for the Audit Logs action identified by `:name`.
    public func listActionSchemas(
        actionName: String,
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<AuditLogSchema> {
        let path = "audit_logs/actions/\(PathEncoding.segment(actionName))/schemas"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<AuditLogSchema>.self
        )
    }

    /// Create Schema
    /// 
    /// Creates a new Audit Log schema used to validate the payload of incoming Audit Log Events. If the `action` does not exist, it will also be created.
    public func createSchema(
        actionName: String,
        targets: [AuditLogSchemaTargetInput],
        actor: AuditLogSchemaActorInput? = nil,
        metadata: [String: AnyCodable]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogSchema {
        let path = "audit_logs/actions/\(PathEncoding.segment(actionName))/schemas"
        var body = EncodableBody()
        body.set("actor", actor)
        body.set("targets", targets)
        body.set("metadata", metadata)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuditLogSchema.self
        )
    }

    /// Create Event
    /// 
    /// Create an Audit Log Event.
    /// 
    /// This API supports idempotency which guarantees that performing the same operation multiple times will have the same result as if the operation were performed only once. This is handy in situations where you may need to retry a request due to a failure or prevent accidental duplicate requests from creating more than one resource.
    /// 
    /// To achieve idempotency, you can add `Idempotency-Key` request header to a Create Event request with a unique string as the value. Each subsequent request matching this unique string will return the same response. We suggest using [v4 UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) for idempotency keys to avoid collisions.
    /// 
    /// Idempotency keys expire after 24 hours. The API will generate a new response if you submit a request with an expired key.
    public func createEvent(
        organizationId: String,
        event: AuditLogEvent,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogEventCreateResponse {
        let path = "audit_logs/events"
        var body = EncodableBody()
        body.set("organization_id", organizationId)
        body.set("event", event)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuditLogEventCreateResponse.self
        )
    }

    /// Create Export
    /// 
    /// Create an Audit Log Export. Exports are scoped to a single organization within a specified date range.
    public func createExport(
        organizationId: String,
        rangeStart: Date,
        rangeEnd: Date,
        actions: [String]? = nil,
        actors: [String]? = nil,
        actorNames: [String]? = nil,
        actorIds: [String]? = nil,
        targets: [String]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogExport {
        let path = "audit_logs/exports"
        var body = EncodableBody()
        body.set("organization_id", organizationId)
        body.set("range_start", rangeStart)
        body.set("range_end", rangeEnd)
        body.set("actions", actions)
        body.set("actors", actors)
        body.set("actor_names", actorNames)
        body.set("actor_ids", actorIds)
        body.set("targets", targets)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuditLogExport.self
        )
    }

    /// Get Export
    /// 
    /// Get an Audit Log Export. The URL will expire after 10 minutes. If the export is needed again at a later time, refetching the export will regenerate the URL.
    public func getExport(
        auditLogExportId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogExport {
        let path = "audit_logs/exports/\(PathEncoding.segment(auditLogExportId))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: AuditLogExport.self
        )
    }
}
