// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Connect API.
public struct Connect: Sendable {
    let transport: Transport

    /// Complete external authentication
    ///
    /// Completes an external authentication flow and returns control to AuthKit. This endpoint is used with [Standalone Connect](https://workos.com/docs/authkit/connect/standalone) to bridge your existing authentication system with the Connect OAuth API infrastructure.
    ///
    /// After successfully authenticating a user in your application, calling this endpoint will:
    ///
    /// - Create or update the user in AuthKit, using the given `id` as its `external_id`.
    /// - Return a `redirect_uri` your application should redirect to in order for AuthKit to complete the flow
    ///
    /// Users are automatically created or updated based on the `id` and `email` provided. If a user with the same `id` exists, their information is updated. Otherwise, a new user is created.
    ///
    /// If you provide a new `id` with an `email` that already belongs to an existing user, the request will fail with an error as email addresses are unique to a user.
    public func completeOauth2(
        externalAuthId: String,
        user: UserObject,
        userConsentOptions: [UserConsentOption]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> ExternalAuthCompleteResponse {
        let path = "authkit/oauth2/complete"
        var body = EncodableBody()
        body.set("external_auth_id", externalAuthId)
        body.set("user", user)
        body.set("user_consent_options", userConsentOptions)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: ExternalAuthCompleteResponse.self
        )
    }

    /// List Connect Applications
    ///
    /// List all Connect Applications in the current environment with optional filtering.
    public func listApplications(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        registrationTypes: [ApplicationsRegistrationTypes]? = nil,
        organizationId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<ConnectApplication> {
        let path = "connect/applications"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let registrationTypes {
            for value in registrationTypes {
                query.append(URLQueryItem(name: "registration_types", value: value.rawValue))
            }
        }
        if let organizationId {
            query.append(URLQueryItem(name: "organization_id", value: organizationId))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<ConnectApplication>.self
        )
    }

    /// Create oauth application.
    public func createOAuthApplication(
        name: String,
        isFirstParty: Bool,
        description: String? = nil,
        scopes: [String]? = nil,
        redirectUris: [RedirectUriInput]? = nil,
        usesPkce: Bool? = nil,
        organizationId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> ConnectApplication {
        let path = "connect/applications"
        var body = EncodableBody()
        body.set("name", name)
        body.set("is_first_party", isFirstParty)
        body.set("description", description)
        body.set("scopes", scopes)
        body.set("redirect_uris", redirectUris)
        body.set("uses_pkce", usesPkce)
        body.set("organization_id", organizationId)
        body.set("application_type", "oauth")
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: ConnectApplication.self
        )
    }

    /// Create m2m application.
    public func createM2MApplication(
        name: String,
        organizationId: String,
        description: String? = nil,
        scopes: [String]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> ConnectApplication {
        let path = "connect/applications"
        var body = EncodableBody()
        body.set("name", name)
        body.set("organization_id", organizationId)
        body.set("description", description)
        body.set("scopes", scopes)
        body.set("application_type", "m2m")
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: ConnectApplication.self
        )
    }

    /// Get a Connect Application
    ///
    /// Retrieve details for a specific Connect Application by ID or client ID.
    public func getApplication(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> ConnectApplication {
        let path = "connect/applications/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: ConnectApplication.self
        )
    }

    /// Update a Connect Application
    ///
    /// Update an existing Connect Application. For OAuth applications, you can update redirect URIs. For all applications, you can update the name, description, and scopes.
    public func updateApplication(
        id: String,
        name: String? = nil,
        description: String? = nil,
        scopes: [String]? = nil,
        redirectUris: [RedirectUriInput]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> ConnectApplication {
        let path = "connect/applications/\(PathEncoding.segment(id))"
        var body = EncodableBody()
        body.set("name", name)
        body.set("description", description)
        body.set("scopes", scopes)
        body.set("redirect_uris", redirectUris)
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: ConnectApplication.self
        )
    }

    /// Delete a Connect Application
    ///
    /// Delete an existing Connect Application.
    public func deleteApplication(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "connect/applications/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }

    /// List Client Secrets for a Connect Application
    ///
    /// List all client secrets associated with a Connect Application.
    public func listApplicationClientSecrets(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> [ApplicationCredentialsListItem] {
        let path = "connect/applications/\(PathEncoding.segment(id))/client_secrets"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: [ApplicationCredentialsListItem].self
        )
    }

    /// Create a new client secret for a Connect Application
    ///
    /// Create new secrets for a Connect Application.
    public func createApplicationClientSecret(
        id: String,
        body: CreateApplicationSecret,
        requestOptions: RequestOptions? = nil
    ) async throws -> NewConnectApplicationSecret {
        let path = "connect/applications/\(PathEncoding.segment(id))/client_secrets"
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: NewConnectApplicationSecret.self
        )
    }

    /// Delete a Client Secret
    ///
    /// Delete (revoke) an existing client secret.
    public func deleteClientSecret(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "connect/client_secrets/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }
}
