// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the DirectorySync API.
public struct DirectorySync: Sendable {
    let transport: Transport

    /// List Directories
    ///
    /// Get a list of all of your existing directories matching the criteria specified.
    public func list(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        organizationId: String? = nil,
        search: String? = nil,
        domain: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<Directory> {
        let path = "directories"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let organizationId {
            query.append(URLQueryItem(name: "organization_id", value: organizationId))
        }
        if let search {
            query.append(URLQueryItem(name: "search", value: search))
        }
        if let domain {
            query.append(URLQueryItem(name: "domain", value: domain))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<Directory>.self
        )
    }

    /// Auto-paginating variant of ``list``: fetches successive
    /// pages as the sequence is iterated.
    public func listAutoPaging(
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        organizationId: String? = nil,
        search: String? = nil,
        domain: String? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<Directory> {
        AutoPagingSequence { cursor in
            try await self.list(
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                organizationId: organizationId,
                search: search,
                domain: domain,
                requestOptions: requestOptions
            )
        }
    }

    /// Get a Directory
    ///
    /// Get the details of an existing directory.
    public func get(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Directory {
        let path = "directories/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: Directory.self
        )
    }

    /// Delete a Directory
    ///
    /// Permanently deletes an existing directory. It cannot be undone.
    public func delete(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "directories/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }

    /// List Directory Groups
    ///
    /// Get a list of all of existing directory groups matching the criteria specified.
    public func listGroups(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        directory: String? = nil,
        user: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<DirectoryGroup> {
        let path = "directory_groups"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let directory {
            query.append(URLQueryItem(name: "directory", value: directory))
        }
        if let user {
            query.append(URLQueryItem(name: "user", value: user))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<DirectoryGroup>.self
        )
    }

    /// Auto-paginating variant of ``listGroups``: fetches successive
    /// pages as the sequence is iterated.
    public func listGroupsAutoPaging(
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        directory: String? = nil,
        user: String? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<DirectoryGroup> {
        AutoPagingSequence { cursor in
            try await self.listGroups(
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                directory: directory,
                user: user,
                requestOptions: requestOptions
            )
        }
    }

    /// Get a Directory Group
    ///
    /// Get the details of an existing Directory Group.
    public func getGroup(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> DirectoryGroup {
        let path = "directory_groups/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: DirectoryGroup.self
        )
    }

    /// List Directory Users
    ///
    /// Get a list of all of existing Directory Users matching the criteria specified.
    public func listUsers(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        directory: String? = nil,
        group: String? = nil,
        idpId: String? = nil,
        email: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<DirectoryUserWithGroups> {
        let path = "directory_users"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let directory {
            query.append(URLQueryItem(name: "directory", value: directory))
        }
        if let group {
            query.append(URLQueryItem(name: "group", value: group))
        }
        if let idpId {
            query.append(URLQueryItem(name: "idp_id", value: idpId))
        }
        if let email {
            query.append(URLQueryItem(name: "email", value: email))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<DirectoryUserWithGroups>.self
        )
    }

    /// Auto-paginating variant of ``listUsers``: fetches successive
    /// pages as the sequence is iterated.
    public func listUsersAutoPaging(
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        directory: String? = nil,
        group: String? = nil,
        idpId: String? = nil,
        email: String? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<DirectoryUserWithGroups> {
        AutoPagingSequence { cursor in
            try await self.listUsers(
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                directory: directory,
                group: group,
                idpId: idpId,
                email: email,
                requestOptions: requestOptions
            )
        }
    }

    /// Get a Directory User
    ///
    /// Get the details of an existing Directory User.
    public func getUser(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> DirectoryUserWithGroups {
        let path = "directory_users/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: DirectoryUserWithGroups.self
        )
    }
}
