// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Events API.
public struct Events: Sendable {
    let transport: Transport

    init(transport: Transport) {
        self.transport = transport
    }

    /// List events
    /// 
    /// List events for the current environment.
    public func list(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        events: [String]? = nil,
        rangeStart: String? = nil,
        rangeEnd: String? = nil,
        organizationId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<EventSchema> {
        let path = "events"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let events {
            for value in events {
                query.append(URLQueryItem(name: "events", value: value))
            }
        }
        if let rangeStart {
            query.append(URLQueryItem(name: "range_start", value: rangeStart))
        }
        if let rangeEnd {
            query.append(URLQueryItem(name: "range_end", value: rangeEnd))
        }
        if let organizationId {
            query.append(URLQueryItem(name: "organization_id", value: organizationId))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<EventSchema>.self
        )
    }
}
