// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Groups API.
public struct Groups: Sendable {
    let transport: Transport

    /// List groups
    ///
    /// Get a paginated list of groups within an organization.
    public func listOrganization(
        organizationId: String,
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<Group> {
        let path = "organizations/\(PathEncoding.segment(organizationId))/groups"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<Group>.self
        )
    }

    /// Auto-paginating variant of ``listOrganization``: fetches successive
    /// pages as the sequence is iterated.
    public func listOrganizationAutoPaging(
        organizationId: String,
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<Group> {
        AutoPagingSequence { cursor in
            try await self.listOrganization(
                organizationId: organizationId,
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                requestOptions: requestOptions
            )
        }
    }

    /// Create a group
    ///
    /// Create a new group within an organization.
    public func createOrganization(
        organizationId: String,
        name: String,
        description: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Group {
        let path = "organizations/\(PathEncoding.segment(organizationId))/groups"
        var body = EncodableBody()
        body.set("name", name)
        body.set("description", description)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: Group.self
        )
    }

    /// Get a group
    ///
    /// Retrieve a group by its ID within an organization.
    public func getOrganization(
        organizationId: String,
        groupId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Group {
        let path =
            "organizations/\(PathEncoding.segment(organizationId))/groups/\(PathEncoding.segment(groupId))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: Group.self
        )
    }

    /// Update a group
    ///
    /// Update an existing group. Only the fields provided in the request body will be updated.
    public func updateOrganization(
        organizationId: String,
        groupId: String,
        name: String? = nil,
        description: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Group {
        let path =
            "organizations/\(PathEncoding.segment(organizationId))/groups/\(PathEncoding.segment(groupId))"
        var body = EncodableBody()
        body.set("name", name)
        body.set("description", description)
        return try await transport.request(
            method: "PATCH",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: Group.self
        )
    }

    /// Delete a group
    ///
    /// Delete a group from an organization.
    public func deleteOrganization(
        organizationId: String,
        groupId: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path =
            "organizations/\(PathEncoding.segment(organizationId))/groups/\(PathEncoding.segment(groupId))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }

    /// List Group members
    ///
    /// Get a list of organization memberships in a group.
    public func listGroupOrganizationMemberships(
        organizationId: String,
        groupId: String,
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<UserOrganizationMembershipBaseListData> {
        let path =
            "organizations/\(PathEncoding.segment(organizationId))/groups/\(PathEncoding.segment(groupId))/organization-memberships"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<UserOrganizationMembershipBaseListData>.self
        )
    }

    /// Auto-paginating variant of ``listGroupOrganizationMemberships``: fetches successive
    /// pages as the sequence is iterated.
    public func listGroupOrganizationMembershipsAutoPaging(
        organizationId: String,
        groupId: String,
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<UserOrganizationMembershipBaseListData> {
        AutoPagingSequence { cursor in
            try await self.listGroupOrganizationMemberships(
                organizationId: organizationId,
                groupId: groupId,
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                requestOptions: requestOptions
            )
        }
    }

    /// Add a member to a Group
    ///
    /// Add an organization membership to a group.
    public func createGroupOrganizationMembership(
        organizationId: String,
        groupId: String,
        organizationMembershipId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Group {
        let path =
            "organizations/\(PathEncoding.segment(organizationId))/groups/\(PathEncoding.segment(groupId))/organization-memberships"
        var body = EncodableBody()
        body.set("organization_membership_id", organizationMembershipId)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: Group.self
        )
    }

    /// Remove a member from a Group
    ///
    /// Remove an organization membership from a group.
    public func deleteGroupOrganizationMembership(
        organizationId: String,
        groupId: String,
        omId: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path =
            "organizations/\(PathEncoding.segment(organizationId))/groups/\(PathEncoding.segment(groupId))/organization-memberships/\(PathEncoding.segment(omId))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }
}
