// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the MultiFactorAuth API.
public struct MultiFactorAuth: Sendable {
    let transport: Transport

    /// Verify Challenge
    ///
    /// Verifies an Authentication Challenge.
    ///
    /// - Parameter id: The unique ID of the Authentication Challenge.
    /// - Parameter code: The one-time code to verify.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func verifyChallenge(
        id: String,
        code: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuthenticationChallengeVerifyResponse {
        let path = "auth/challenges/\(PathEncoding.segment(id))/verify"
        var body = EncodableBody()
        body.set("code", code)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuthenticationChallengeVerifyResponse.self
        )
    }

    /// Enroll Factor
    ///
    /// Enrolls an Authentication Factor to be used as an additional factor of authentication. The returned ID should be used to create an authentication Challenge.
    ///
    /// - Parameter type: The type of factor to enroll.
    /// - Parameter phoneNumber: Required when type is 'sms'.
    /// - Parameter totpIssuer: Required when type is 'totp'.
    /// - Parameter totpUser: Required when type is 'totp'.
    /// - Parameter userId: The ID of the user to associate the factor with.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func enrollFactor(
        type: AuthenticationFactorsCreateRequestType,
        phoneNumber: String? = nil,
        totpIssuer: String? = nil,
        totpUser: String? = nil,
        userId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuthenticationFactorEnrolled {
        let path = "auth/factors/enroll"
        var body = EncodableBody()
        body.set("type", type)
        body.set("phone_number", phoneNumber)
        body.set("totp_issuer", totpIssuer)
        body.set("totp_user", totpUser)
        body.set("user_id", userId)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuthenticationFactorEnrolled.self
        )
    }

    /// Get Factor
    ///
    /// Gets an Authentication Factor.
    ///
    /// - Parameter id: The unique ID of the Factor.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func getFactor(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuthenticationFactor {
        let path = "auth/factors/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: AuthenticationFactor.self
        )
    }

    /// Delete Factor
    ///
    /// Permanently deletes an Authentication Factor. It cannot be undone.
    ///
    /// - Parameter id: The unique ID of the Factor.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func deleteFactor(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "auth/factors/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }

    /// Challenge Factor
    ///
    /// Creates a Challenge for an Authentication Factor.
    ///
    /// - Parameter id: The unique ID of the Authentication Factor to be challenged.
    /// - Parameter smsTemplate: A custom template for the SMS message. Use the {{code}} placeholder to include the verification code.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func challengeFactor(
        id: String,
        smsTemplate: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuthenticationChallenge {
        let path = "auth/factors/\(PathEncoding.segment(id))/challenge"
        var body = EncodableBody()
        body.set("sms_template", smsTemplate)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: AuthenticationChallenge.self
        )
    }

    /// List authentication factors
    ///
    /// Lists the [authentication factors](https://workos.com/docs/reference/authkit/mfa/authentication-factor) for a user.
    ///
    /// - Parameter userlandUserId: The ID of the [user](https://workos.com/docs/reference/authkit/user).
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    /// - Parameter after: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listUserAuthFactors(
        userlandUserId: String,
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<AuthenticationFactor> {
        let path = "user_management/users/\(PathEncoding.segment(userlandUserId))/auth_factors"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<AuthenticationFactor>.self
        )
    }

    /// Auto-paginating variant of `listUserAuthFactors`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter userlandUserId: The ID of the [user](https://workos.com/docs/reference/authkit/user).
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listUserAuthFactorsAutoPaging(
        userlandUserId: String,
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<AuthenticationFactor> {
        AutoPagingSequence { cursor in
            try await self.listUserAuthFactors(
                userlandUserId: userlandUserId,
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                requestOptions: requestOptions
            )
        }
    }

    /// Enroll an authentication factor
    ///
    /// Enrolls a user in a new [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor).
    ///
    /// - Parameter userlandUserId: The ID of the [user](https://workos.com/docs/reference/authkit/user).
    /// - Parameter type: The type of the factor to enroll.
    /// - Parameter totpIssuer: Your application or company name displayed in the user's authenticator app.
    /// - Parameter totpUser: The user's account name displayed in their authenticator app.
    /// - Parameter totpSecret: The Base32-encoded shared secret for TOTP factors. This can be provided when creating the auth factor, otherwise it will be generated. The algorithm used to derive TOTP codes is SHA-1, the code length is 6 digits, and the timestep is 30 seconds – the secret must be compatible with these parameters.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func createUserAuthFactor(
        userlandUserId: String,
        type: String,
        totpIssuer: String? = nil,
        totpUser: String? = nil,
        totpSecret: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> UserAuthenticationFactorEnrollResponse {
        let path = "user_management/users/\(PathEncoding.segment(userlandUserId))/auth_factors"
        var body = EncodableBody()
        body.set("type", type)
        body.set("totp_issuer", totpIssuer)
        body.set("totp_user", totpUser)
        body.set("totp_secret", totpSecret)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: UserAuthenticationFactorEnrollResponse.self
        )
    }
}
