// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the OrganizationMembershipResource API.
public struct OrganizationMembershipResource: Sendable {
    let transport: Transport

    /// List organization memberships
    ///
    /// Get a list of all organization memberships matching the criteria specified. At least one of `user_id` or `organization_id` must be provided. By default only active memberships are returned. Use the `statuses` parameter to filter by other statuses.
    ///
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter after: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter organizationId: The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
    /// - Parameter statuses: Filter by the status of the organization membership. Array including any of `active`, `inactive`, or `pending`.
    /// - Parameter userId: The ID of the [user](https://workos.com/docs/reference/authkit/user).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func list(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        organizationId: String? = nil,
        statuses: [UserManagementOrganizationMembershipStatuses]? = nil,
        userId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<UserOrganizationMembership> {
        let path = "user_management/organization_memberships"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let organizationId {
            query.append(URLQueryItem(name: "organization_id", value: organizationId))
        }
        if let statuses {
            for value in statuses {
                query.append(URLQueryItem(name: "statuses", value: value.rawValue))
            }
        }
        if let userId {
            query.append(URLQueryItem(name: "user_id", value: userId))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<UserOrganizationMembership>.self
        )
    }

    /// Auto-paginating variant of `list`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter organizationId: The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
    /// - Parameter statuses: Filter by the status of the organization membership. Array including any of `active`, `inactive`, or `pending`.
    /// - Parameter userId: The ID of the [user](https://workos.com/docs/reference/authkit/user).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listAutoPaging(
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        organizationId: String? = nil,
        statuses: [UserManagementOrganizationMembershipStatuses]? = nil,
        userId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<UserOrganizationMembership> {
        AutoPagingSequence { cursor in
            try await self.list(
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                organizationId: organizationId,
                statuses: statuses,
                userId: userId,
                requestOptions: requestOptions
            )
        }
    }

    /// Create an organization membership
    ///
    /// Creates a new `active` organization membership for the given organization and user.
    ///
    /// Calling this API with an organization and user that match an `inactive` organization membership will activate the membership with the specified role(s).
    ///
    /// - Parameter userId: The ID of the [user](https://workos.com/docs/reference/authkit/user).
    /// - Parameter organizationId: The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
    /// - Parameter roleSlug: A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`.
    /// - Parameter roleSlugs: An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func create(
        userId: String,
        organizationId: String,
        roleSlug: String? = nil,
        roleSlugs: [String]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> OrganizationMembership {
        let path = "user_management/organization_memberships"
        var body = EncodableBody()
        body.set("user_id", userId)
        body.set("organization_id", organizationId)
        body.set("role_slug", roleSlug)
        body.set("role_slugs", roleSlugs)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: OrganizationMembership.self
        )
    }

    /// Get an organization membership
    ///
    /// Get the details of an existing organization membership.
    ///
    /// - Parameter id: The unique ID of the organization membership.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func get(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> UserOrganizationMembership {
        let path = "user_management/organization_memberships/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: UserOrganizationMembership.self
        )
    }

    /// Update an organization membership
    ///
    /// Update the details of an existing organization membership.
    ///
    /// - Parameter id: The unique ID of the organization membership.
    /// - Parameter roleSlug: A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`.
    /// - Parameter roleSlugs: An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func update(
        id: String,
        roleSlug: String? = nil,
        roleSlugs: [String]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> UserOrganizationMembership {
        let path = "user_management/organization_memberships/\(PathEncoding.segment(id))"
        var body = EncodableBody()
        body.set("role_slug", roleSlug)
        body.set("role_slugs", roleSlugs)
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: UserOrganizationMembership.self
        )
    }

    /// Delete an organization membership
    ///
    /// Permanently deletes an existing organization membership. It cannot be undone.
    ///
    /// - Parameter id: The unique ID of the organization membership.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func delete(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "user_management/organization_memberships/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }

    /// Deactivate an organization membership
    ///
    /// Deactivates an `active` organization membership. Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful deactivation.
    ///
    /// - Deactivating an `inactive` membership is a no-op and does not emit an event.
    /// - Deactivating a `pending` membership returns an error. This membership should be [deleted](https://workos.com/docs/reference/authkit/organization-membership/delete) instead.
    ///
    /// See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
    ///
    /// - Parameter id: The unique ID of the organization membership.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func deactivate(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> OrganizationMembership {
        let path = "user_management/organization_memberships/\(PathEncoding.segment(id))/deactivate"
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: OrganizationMembership.self
        )
    }

    /// Reactivate an organization membership
    ///
    /// Reactivates an `inactive` organization membership, retaining the pre-existing role(s). Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful reactivation.
    ///
    /// - Reactivating an `active` membership is a no-op and does not emit an event.
    /// - Reactivating a `pending` membership returns an error. The user needs to [accept the invitation](https://workos.com/docs/authkit/invitations) instead.
    ///
    /// See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
    ///
    /// - Parameter id: The unique ID of the organization membership.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func reactivate(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> UserOrganizationMembership {
        let path = "user_management/organization_memberships/\(PathEncoding.segment(id))/reactivate"
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: UserOrganizationMembership.self
        )
    }

    /// List groups
    ///
    /// Get a list of groups that an organization membership belongs to.
    ///
    /// - Parameter omId: Unique identifier of the Organization Membership.
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter after: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listGroups(
        omId: String,
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<Group> {
        let path = "user_management/organization_memberships/\(PathEncoding.segment(omId))/groups"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<Group>.self
        )
    }

    /// Auto-paginating variant of `listGroups`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter omId: Unique identifier of the Organization Membership.
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listGroupsAutoPaging(
        omId: String,
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<Group> {
        AutoPagingSequence { cursor in
            try await self.listGroups(
                omId: omId,
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                requestOptions: requestOptions
            )
        }
    }
}
