// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Organizations API.
public struct Organizations: Sendable {
    let transport: Transport

    /// List Organizations
    ///
    /// Get a list of all of your existing organizations matching the criteria specified.
    ///
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter after: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter domains: The domains of an Organization. Any Organization with a matching domain will be returned.
    /// - Parameter search: Searchable text for an Organization. Matches against the organization name.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func list(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        domains: [String]? = nil,
        search: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<Organization> {
        let path = "organizations"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let domains {
            for value in domains {
                query.append(URLQueryItem(name: "domains", value: value))
            }
        }
        if let search {
            query.append(URLQueryItem(name: "search", value: search))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<Organization>.self
        )
    }

    /// Auto-paginating variant of `list`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter domains: The domains of an Organization. Any Organization with a matching domain will be returned.
    /// - Parameter search: Searchable text for an Organization. Matches against the organization name.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listAutoPaging(
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        domains: [String]? = nil,
        search: String? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<Organization> {
        AutoPagingSequence { cursor in
            try await self.list(
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                domains: domains,
                search: search,
                requestOptions: requestOptions
            )
        }
    }

    /// Create an Organization
    ///
    /// Creates a new organization in the current environment.
    ///
    /// - Parameter name: The name of the organization.
    /// - Parameter allowProfilesOutsideOrganization: Whether the organization allows profiles from outside the organization to sign in.
    /// - Parameter domains: The domains associated with the organization. Deprecated in favor of `domain_data`.
    /// - Parameter domainData: The domains associated with the organization, including verification state.
    /// - Parameter metadata: Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization.
    /// - Parameter externalId: An external identifier for the Organization.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func create(
        name: String,
        allowProfilesOutsideOrganization: Bool? = nil,
        domains: [String]? = nil,
        domainData: [OrganizationDomainData]? = nil,
        metadata: [String: String]? = nil,
        externalId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Organization {
        let path = "organizations"
        var body = EncodableBody()
        body.set("name", name)
        body.set("allow_profiles_outside_organization", allowProfilesOutsideOrganization)
        body.set("domains", domains)
        body.set("domain_data", domainData)
        body.set("metadata", metadata)
        body.set("external_id", externalId)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: Organization.self
        )
    }

    /// Get an Organization by External ID
    ///
    /// Get the details of an existing organization by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
    ///
    /// - Parameter externalId: The external ID of the Organization.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func getByExternalId(
        externalId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Organization {
        let path = "organizations/external_id/\(PathEncoding.segment(externalId))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: Organization.self
        )
    }

    /// Get an Organization
    ///
    /// Get the details of an existing organization.
    ///
    /// - Parameter id: Unique identifier of the Organization.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func get(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Organization {
        let path = "organizations/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: Organization.self
        )
    }

    /// Update an Organization
    ///
    /// Updates an organization in the current environment.
    ///
    /// - Parameter id: Unique identifier of the Organization.
    /// - Parameter name: The name of the organization.
    /// - Parameter allowProfilesOutsideOrganization: Whether the organization allows profiles from outside the organization to sign in.
    /// - Parameter domains: Deprecated. The domains associated with the organization. Deprecated in favor of `domain_data`.
    /// - Parameter domainData: The domains associated with the organization, including verification state.
    /// - Parameter stripeCustomerId: The Stripe customer ID associated with the organization.
    /// - Parameter metadata: Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization.
    /// - Parameter externalId: An external identifier for the Organization.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func update(
        id: String,
        name: String? = nil,
        allowProfilesOutsideOrganization: Bool? = nil,
        domains: [String]? = nil,
        domainData: [OrganizationDomainData]? = nil,
        stripeCustomerId: String? = nil,
        metadata: [String: String]? = nil,
        externalId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Organization {
        let path = "organizations/\(PathEncoding.segment(id))"
        var body = EncodableBody()
        body.set("name", name)
        body.set("allow_profiles_outside_organization", allowProfilesOutsideOrganization)
        body.set("domains", domains)
        body.set("domain_data", domainData)
        body.set("stripe_customer_id", stripeCustomerId)
        body.set("metadata", metadata)
        body.set("external_id", externalId)
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: Organization.self
        )
    }

    /// Delete an Organization
    ///
    /// Permanently deletes an organization in the current environment. It cannot be undone.
    ///
    /// - Parameter id: Unique identifier of the Organization.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func delete(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "organizations/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }

    /// Get Audit Log Configuration
    ///
    /// Get the unified view of audit log trail and stream configuration for an organization.
    ///
    /// - Parameter id: Unique identifier of the Organization.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func getAuditLogConfiguration(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AuditLogConfiguration {
        let path = "organizations/\(PathEncoding.segment(id))/audit_log_configuration"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: AuditLogConfiguration.self
        )
    }

    /// List authorized applications
    ///
    /// Get a list of all Connect applications that users in the organization have authorized.
    ///
    /// - Parameter organizationId: The ID of the organization.
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter after: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listAuthorizedApplications(
        organizationId: String,
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<OrganizationAuthorizedConnectApplicationListData> {
        let path = "organizations/\(PathEncoding.segment(organizationId))/authorized_applications"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<OrganizationAuthorizedConnectApplicationListData>.self
        )
    }

    /// Auto-paginating variant of `listAuthorizedApplications`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter organizationId: The ID of the organization.
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listAuthorizedApplicationsAutoPaging(
        organizationId: String,
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<OrganizationAuthorizedConnectApplicationListData> {
        AutoPagingSequence { cursor in
            try await self.listAuthorizedApplications(
                organizationId: organizationId,
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                requestOptions: requestOptions
            )
        }
    }
}
