// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Vault API.
public struct Vault: Sendable {
    let transport: Transport

    /// Create a data key
    ///
    /// Generate an isolated encryption key for local encryption operations.
    ///
    /// - Parameter context: Map of values used to determine the encryption key.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func createDataKey(
        context: [String: String],
        requestOptions: RequestOptions? = nil
    ) async throws -> CreateDataKeyResponse {
        let path = "vault/v1/keys/data-key"
        var body = EncodableBody()
        body.set("context", context)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: CreateDataKeyResponse.self
        )
    }

    /// Decrypt a data key
    ///
    /// Decrypt a previously encrypted data key from WorkOS Vault.
    ///
    /// - Parameter keys: Base64-encoded encrypted data key to decrypt.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func createDecrypt(
        keys: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> DecryptResponse {
        let path = "vault/v1/keys/decrypt"
        var body = EncodableBody()
        body.set("keys", keys)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: DecryptResponse.self
        )
    }

    /// Re-encrypt a data key
    ///
    /// Decrypt an existing data key and re-encrypt it under a new key context.
    ///
    /// - Parameter context: Map of values used to determine the new encryption key.
    /// - Parameter encryptedKeys: Base64-encoded encrypted data key blob to re-encrypt.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func createRekey(
        context: [String: String],
        encryptedKeys: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> CreateDataKeyResponse {
        let path = "vault/v1/keys/rekey"
        var body = EncodableBody()
        body.set("context", context)
        body.set("encrypted_keys", encryptedKeys)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: CreateDataKeyResponse.self
        )
    }

    /// List objects
    ///
    /// List all encrypted objects with cursor-based pagination.
    ///
    /// - Parameter limit: Upper limit on the number of objects to return.
    /// - Parameter before: Cursor for the previous page of results.
    /// - Parameter after: Cursor for the next page of results.
    /// - Parameter order: Sort direction for results.
    /// - Parameter search: Filter results by name or structured search JSON.
    /// - Parameter updatedAfter: ISO 8601 timestamp to filter by last modified time.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listKv(
        limit: Int? = nil,
        before: String? = nil,
        after: String? = nil,
        order: VaultOrder? = nil,
        search: String? = nil,
        updatedAfter: Date? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<ObjectSummary> {
        let path = "vault/v1/kv"
        var query: [URLQueryItem] = []
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        if let search {
            query.append(URLQueryItem(name: "search", value: search))
        }
        if let updatedAfter {
            query.append(URLQueryItem(name: "updatedAfter", value: "\(updatedAfter)"))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<ObjectSummary>.self
        )
    }

    /// Auto-paginating variant of `listKv`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter limit: Upper limit on the number of objects to return.
    /// - Parameter before: Cursor for the previous page of results.
    /// - Parameter order: Sort direction for results.
    /// - Parameter search: Filter results by name or structured search JSON.
    /// - Parameter updatedAfter: ISO 8601 timestamp to filter by last modified time.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listKvAutoPaging(
        limit: Int? = nil,
        before: String? = nil,
        order: VaultOrder? = nil,
        search: String? = nil,
        updatedAfter: Date? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<ObjectSummary> {
        AutoPagingSequence { cursor in
            try await self.listKv(
                limit: limit,
                before: before,
                after: cursor,
                order: order,
                search: search,
                updatedAfter: updatedAfter,
                requestOptions: requestOptions
            )
        }
    }

    /// Create an object
    ///
    /// Encrypt and store a new key-value object.
    ///
    /// - Parameter keyContext: Map of values used to determine the encryption key.
    /// - Parameter name: Unique name for the object.
    /// - Parameter value: Plaintext data to encrypt and store.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func createKv(
        keyContext: [String: String],
        name: String,
        value: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> ObjectMetadata {
        let path = "vault/v1/kv"
        var body = EncodableBody()
        body.set("key_context", keyContext)
        body.set("name", name)
        body.set("value", value)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: ObjectMetadata.self
        )
    }

    /// Read an object by name
    ///
    /// Fetch and decrypt an object by its unique name.
    ///
    /// - Parameter name: Unique name of the object.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func getName(
        name: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> VaultObject {
        let path = "vault/v1/kv/name/\(PathEncoding.segment(name))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: VaultObject.self
        )
    }

    /// Read an object by ID
    ///
    /// Fetch and decrypt an object by its unique identifier.
    ///
    /// - Parameter id: Unique identifier of the object.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func getKv(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> VaultObject {
        let path = "vault/v1/kv/\(PathEncoding.segment(id))"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: VaultObject.self
        )
    }

    /// Update an object
    ///
    /// Update the value of an existing encrypted object.
    ///
    /// - Parameter id: Unique identifier of the object.
    /// - Parameter value: New plaintext value.
    /// - Parameter versionCheck: ID of the expected current version for optimistic locking.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func updateKv(
        id: String,
        value: String,
        versionCheck: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> ObjectWithoutValue {
        let path = "vault/v1/kv/\(PathEncoding.segment(id))"
        var body = EncodableBody()
        body.set("value", value)
        body.set("version_check", versionCheck)
        return try await transport.request(
            method: "PUT",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: ObjectWithoutValue.self
        )
    }

    /// Delete an object
    ///
    /// Delete an encrypted object.
    ///
    /// - Parameter id: Unique identifier of the object.
    /// - Parameter versionCheck: Expected current version for optimistic locking.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func deleteKv(
        id: String,
        versionCheck: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "vault/v1/kv/\(PathEncoding.segment(id))"
        var query: [URLQueryItem] = []
        if let versionCheck {
            query.append(URLQueryItem(name: "version_check", value: versionCheck))
        }
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: query,
            body: nil,
            options: requestOptions
        )
    }

    /// Describe an object
    ///
    /// Fetch metadata for an object without decrypting it.
    ///
    /// - Parameter id: Unique identifier of the object.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listKvMetadata(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> ObjectWithoutValue {
        let path = "vault/v1/kv/\(PathEncoding.segment(id))/metadata"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: ObjectWithoutValue.self
        )
    }

    /// List object versions
    ///
    /// Retrieve all versions for a specific object.
    ///
    /// - Parameter id: Unique identifier of the object.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listKvVersions(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> VersionListResponse {
        let path = "vault/v1/kv/\(PathEncoding.segment(id))/versions"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            body: nil,
            options: requestOptions,
            as: VersionListResponse.self
        )
    }
}
