// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Webhooks API.
public struct Webhooks: Sendable {
    let transport: Transport

    /// List Webhook Endpoints
    ///
    /// Get a list of all of your existing webhook endpoints.
    ///
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter after: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listEndpoints(
        before: String? = nil,
        after: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<WebhookEndpoint> {
        let path = "webhook_endpoints"
        var query: [URLQueryItem] = []
        if let before {
            query.append(URLQueryItem(name: "before", value: before))
        }
        if let after {
            query.append(URLQueryItem(name: "after", value: after))
        }
        if let limit {
            query.append(URLQueryItem(name: "limit", value: "\(limit)"))
        }
        if let order {
            query.append(URLQueryItem(name: "order", value: order.rawValue))
        }
        return try await transport.request(
            method: "GET",
            path: path,
            query: query,
            body: nil,
            options: requestOptions,
            as: Page<WebhookEndpoint>.self
        )
    }

    /// Auto-paginating variant of `listEndpoints`: fetches successive
    /// pages as the sequence is iterated.
    ///
    /// - Parameter before: An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    /// - Parameter limit: Upper limit on the number of objects to return, between `1` and `100`.
    /// - Parameter order: Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func listEndpointsAutoPaging(
        before: String? = nil,
        limit: Int? = nil,
        order: PaginationOrder? = nil,
        requestOptions: RequestOptions? = nil
    ) -> AutoPagingSequence<WebhookEndpoint> {
        AutoPagingSequence { cursor in
            try await self.listEndpoints(
                before: before,
                after: cursor,
                limit: limit,
                order: order,
                requestOptions: requestOptions
            )
        }
    }

    /// Create a Webhook Endpoint
    ///
    /// Create a new webhook endpoint to receive event notifications.
    ///
    /// - Parameter endpointUrl: The HTTPS URL where webhooks will be sent.
    /// - Parameter events: The events that the Webhook Endpoint is subscribed to.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func createEndpoint(
        endpointUrl: String,
        events: [CreateWebhookEndpointEvents],
        requestOptions: RequestOptions? = nil
    ) async throws -> WebhookEndpoint {
        let path = "webhook_endpoints"
        var body = EncodableBody()
        body.set("endpoint_url", endpointUrl)
        body.set("events", events)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: WebhookEndpoint.self
        )
    }

    /// Update a Webhook Endpoint
    ///
    /// Update the properties of an existing webhook endpoint.
    ///
    /// - Parameter id: Unique identifier of the Webhook Endpoint.
    /// - Parameter endpointUrl: The HTTPS URL where webhooks will be sent.
    /// - Parameter status: Whether the Webhook Endpoint is enabled or disabled.
    /// - Parameter events: The events that the Webhook Endpoint is subscribed to.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func updateEndpoint(
        id: String,
        endpointUrl: String? = nil,
        status: UpdateWebhookEndpointStatus? = nil,
        events: [UpdateWebhookEndpointEvents]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> WebhookEndpoint {
        let path = "webhook_endpoints/\(PathEncoding.segment(id))"
        var body = EncodableBody()
        body.set("endpoint_url", endpointUrl)
        body.set("status", status)
        body.set("events", events)
        return try await transport.request(
            method: "PATCH",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: WebhookEndpoint.self
        )
    }

    /// Delete a Webhook Endpoint
    ///
    /// Delete an existing webhook endpoint.
    ///
    /// - Parameter id: Unique identifier of the Webhook Endpoint.
    /// - Parameter requestOptions: Per-request overrides (idempotency key, API key, headers, timeout).
    public func deleteEndpoint(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "webhook_endpoints/\(PathEncoding.segment(id))"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            query: [],
            body: nil,
            options: requestOptions
        )
    }
}
