// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AccessTokenAgentRegistrationCredentialIssuedDataDetail: Codable, Sendable, Equatable {
    /// The kind of credential issued.
    public let kind: String
    /// The JWT ID of the issued access token.
    public let jti: String
    /// The timestamp when the access token expires.
    public let expiresAt: AnyCodable

    public init(
        kind: String,
        jti: String,
        expiresAt: AnyCodable
    ) {
        self.kind = kind
        self.jti = jti
        self.expiresAt = expiresAt
    }

    private enum CodingKeys: String, CodingKey {
        case kind
        case jti
        case expiresAt = "expires_at"
    }
}
