// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AccountSelectionRequiredError: Codable, Sendable, Equatable {
    /// Indicates that several connected accounts match and the request must name one.
    public let code: String
    /// A human-readable explanation of the ambiguity.
    public let message: String

    public init(
        code: String,
        message: String
    ) {
        self.code = code
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case code
        case message
    }
}
