// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct ActionAuthenticationDeniedData: Codable, Sendable, Equatable {
    /// The ID of the action endpoint.
    public let actionEndpointId: String
    /// The ID of the action execution.
    public let actionExecutionId: String
    /// The type of action that was denied.
    public let type: String
    /// The verdict of the action.
    public let verdict: String
    /// The ID of the user.
    public let userId: String
    /// The ID of the organization.
    public let organizationId: String?
    /// The email address of the user.
    public let email: String
    /// The IP address of the request.
    public let ipAddress: String?
    /// The user agent of the request.
    public let userAgent: String?

    public init(
        actionEndpointId: String,
        actionExecutionId: String,
        type: String,
        verdict: String,
        userId: String,
        email: String,
        organizationId: String? = nil,
        ipAddress: String? = nil,
        userAgent: String? = nil
    ) {
        self.actionEndpointId = actionEndpointId
        self.actionExecutionId = actionExecutionId
        self.type = type
        self.verdict = verdict
        self.userId = userId
        self.organizationId = organizationId
        self.email = email
        self.ipAddress = ipAddress
        self.userAgent = userAgent
    }

    private enum CodingKeys: String, CodingKey {
        case actionEndpointId = "action_endpoint_id"
        case actionExecutionId = "action_execution_id"
        case type
        case verdict
        case userId = "user_id"
        case organizationId = "organization_id"
        case email
        case ipAddress = "ip_address"
        case userAgent = "user_agent"
    }
}
