// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The user or API key that performed an action.
public struct Actor: Codable, Sendable, Equatable {
    /// Unique identifier of the actor.
    public let id: String
    /// Display name of the actor.
    public let name: String

    public init(
        id: String,
        name: String
    ) {
        self.id = id
        self.name = name
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
    }
}
