// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AgentBlueprintUpdatedData: Codable, Sendable, Equatable {
    /// Distinguishes the agent blueprint object.
    public let object: String
    /// Unique identifier of the agent blueprint.
    public let id: String
    /// Human-readable name of the agent blueprint.
    public let name: String
    /// Human-readable description of the agent blueprint.
    public let description: String?
    /// Permission slugs forming the ceiling on what sessions minted from this blueprint may do.
    public let permissions: [String]
    /// Who may mint sessions from this blueprint.
    public let invocableBy: AgentBlueprintUpdatedDataInvocableBy
    /// Token and session lifetimes for sessions minted from this blueprint.
    public let sessionSettings: AgentBlueprintUpdatedDataSessionSetting
    /// The timestamp when the agent blueprint was created.
    public let createdAt: String
    /// The timestamp when the agent blueprint was last updated.
    public let updatedAt: String

    public init(
        object: String,
        id: String,
        name: String,
        permissions: [String],
        invocableBy: AgentBlueprintUpdatedDataInvocableBy,
        sessionSettings: AgentBlueprintUpdatedDataSessionSetting,
        createdAt: String,
        updatedAt: String,
        description: String? = nil
    ) {
        self.object = object
        self.id = id
        self.name = name
        self.description = description
        self.permissions = permissions
        self.invocableBy = invocableBy
        self.sessionSettings = sessionSettings
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case name
        case description
        case permissions
        case invocableBy = "invocable_by"
        case sessionSettings = "session_settings"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
