// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AgentAdminLinkClaimAttemptToExternalUserRequest: Codable, Sendable, Equatable {
    /// The operation to perform on the claim attempt. Currently only `link_external_user` is supported.
    public let type: String
    /// The token identifying the claim attempt.
    public let claimAttemptToken: String
    /// The user to attach to the claim attempt, identified by email and external ID.
    public let user: AgentAdminLinkClaimAttemptToExternalUserRequestUser
    /// The organization to place the agent in. Required when the user belongs to more than one organization.
    public let organizationId: String?

    public init(
        type: String,
        claimAttemptToken: String,
        user: AgentAdminLinkClaimAttemptToExternalUserRequestUser,
        organizationId: String? = nil
    ) {
        self.type = type
        self.claimAttemptToken = claimAttemptToken
        self.user = user
        self.organizationId = organizationId
    }

    private enum CodingKeys: String, CodingKey {
        case type
        case claimAttemptToken = "claim_attempt_token"
        case user
        case organizationId = "organization_id"
    }
}
