// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AgentRegistrationClaim: Codable, Sendable, Equatable {
    /// Unique identifier of the claim.
    public let id: String
    /// The completion record for the claim, or `null` if the claim has not been completed.
    public let claimCompletion: AgentRegistrationClaimClaimCompletion?
    /// The timestamp when the claim was created.
    public let createdAt: Date
    /// The timestamp when the claim was last updated.
    public let updatedAt: Date
    /// The timestamp when the claim expires.
    public let expiresAt: Date

    public init(
        id: String,
        createdAt: Date,
        updatedAt: Date,
        expiresAt: Date,
        claimCompletion: AgentRegistrationClaimClaimCompletion? = nil
    ) {
        self.id = id
        self.claimCompletion = claimCompletion
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.expiresAt = expiresAt
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case claimCompletion = "claim_completion"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case expiresAt = "expires_at"
    }
}
