// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AgentRegistrationExpiredData: Codable, Sendable, Equatable {
    /// The agent registration that expired.
    public let agentRegistrationId: String

    public init(
        agentRegistrationId: String
    ) {
        self.agentRegistrationId = agentRegistrationId
    }

    private enum CodingKeys: String, CodingKey {
        case agentRegistrationId = "agent_registration_id"
    }
}
