// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AgentRegistrationClaimAttemptCreatedData: Codable, Sendable, Equatable {
    /// Distinguishes the agent registration claim attempt object.
    public let object: String
    /// Unique identifier of the agent registration claim attempt.
    public let id: String
    /// The ID of the agent registration.
    public let agentRegistrationId: String
    /// The ID of the agent registration claim.
    public let agentRegistrationClaimId: String
    /// The login hint for the claim attempt.
    public let loginHint: String
    /// The timestamp when the claim attempt expires.
    public let expiresAt: String
    /// The timestamp when the claim attempt was created.
    public let createdAt: String
    /// The timestamp when the claim attempt was last updated.
    public let updatedAt: String

    public init(
        object: String,
        id: String,
        agentRegistrationId: String,
        agentRegistrationClaimId: String,
        loginHint: String,
        expiresAt: String,
        createdAt: String,
        updatedAt: String
    ) {
        self.object = object
        self.id = id
        self.agentRegistrationId = agentRegistrationId
        self.agentRegistrationClaimId = agentRegistrationClaimId
        self.loginHint = loginHint
        self.expiresAt = expiresAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case agentRegistrationId = "agent_registration_id"
        case agentRegistrationClaimId = "agent_registration_claim_id"
        case loginHint = "login_hint"
        case expiresAt = "expires_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
