// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AgentToken: Codable, Sendable, Equatable {
    /// The agent access token (a JWT) carrying the effective permissions.
    public let accessToken: String
    /// Always `Bearer`.
    public let tokenType: String
    /// Number of seconds until the access token expires.
    public let expiresIn: Int
    /// Single-use refresh token for rotating the access token within the session lifetime.
    public let refreshToken: String
    /// The agent instance the session belongs to.
    public let agentInstanceId: String
    /// Whether this mint created the agent instance: `true` only for the mint that inserted the row, `false` when an existing instance was reused (including when a concurrent mint inserted it first).
    public let newInstance: Bool
    /// The backing agent instance session.
    public let agentInstanceSessionId: String
    /// The effective permission slugs carried by the token.
    public let permissions: [String]

    public init(
        accessToken: String,
        tokenType: String,
        expiresIn: Int,
        refreshToken: String,
        agentInstanceId: String,
        newInstance: Bool,
        agentInstanceSessionId: String,
        permissions: [String]
    ) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.refreshToken = refreshToken
        self.agentInstanceId = agentInstanceId
        self.newInstance = newInstance
        self.agentInstanceSessionId = agentInstanceSessionId
        self.permissions = permissions
    }

    private enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case refreshToken = "refresh_token"
        case agentInstanceId = "agent_instance_id"
        case newInstance = "new_instance"
        case agentInstanceSessionId = "agent_instance_session_id"
        case permissions
    }
}
