// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AgentBlueprintsCreateRequest: Codable, Sendable, Equatable {
    /// Human-readable name of the agent blueprint.
    public let name: String
    /// Human-readable description of the agent blueprint.
    public let description: String?
    /// Permission slugs forming the ceiling on what sessions minted from this blueprint may do. Each slug must exist in the environment.
    public let permissions: [String]?
    /// Who may mint sessions from this blueprint.
    public let invocableBy: AgentBlueprintsCreateRequestInvocableBy?
    /// Token and session lifetimes for sessions minted from this blueprint.
    public let sessionSettings: AgentBlueprintsCreateRequestSessionSetting

    public init(
        name: String,
        sessionSettings: AgentBlueprintsCreateRequestSessionSetting,
        description: String? = nil,
        permissions: [String]? = nil,
        invocableBy: AgentBlueprintsCreateRequestInvocableBy? = nil
    ) {
        self.name = name
        self.description = description
        self.permissions = permissions
        self.invocableBy = invocableBy
        self.sessionSettings = sessionSettings
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case description
        case permissions
        case invocableBy = "invocable_by"
        case sessionSettings = "session_settings"
    }
}
