// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Who may mint sessions from this blueprint.
public struct AgentBlueprintsCreateRequestInvocableBy: Codable, Sendable, Equatable {
    /// Role slugs whose members may mint user-delegated sessions from this blueprint. An empty list allows any member.
    public let roleSlugs: [String]?
    /// Organizations in which sessions may be minted from this blueprint, enforced on user-delegated, autonomous, and agent-delegated mints. An empty list allows any organization in the environment.
    public let organizationIds: [String]?

    public init(
        roleSlugs: [String]? = nil,
        organizationIds: [String]? = nil
    ) {
        self.roleSlugs = roleSlugs
        self.organizationIds = organizationIds
    }

    private enum CodingKeys: String, CodingKey {
        case roleSlugs = "role_slugs"
        case organizationIds = "organization_ids"
    }
}
