// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AgentBlueprintDeletedData: Codable, Sendable, Equatable {
    /// Distinguishes the agent blueprint object.
    public let object: String
    /// Unique identifier of the agent blueprint.
    public let id: String
    /// Human-readable name of the agent blueprint.
    public let name: String
    /// The timestamp when the agent blueprint was created.
    public let createdAt: String
    /// The timestamp when the agent blueprint was last updated.
    public let updatedAt: String

    public init(
        object: String,
        id: String,
        name: String,
        createdAt: String,
        updatedAt: String
    ) {
        self.object = object
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
