// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Who may mint sessions from this blueprint.
public struct AgentBlueprintInvocableBy: Codable, Sendable, Equatable {
    /// Role slugs whose members may mint user-delegated sessions from this blueprint.
    public let roleSlugs: [String]
    /// Organizations in which sessions may be minted from this blueprint, enforced on user-delegated, autonomous, and agent-delegated mints.
    public let organizationIds: [String]

    public init(
        roleSlugs: [String],
        organizationIds: [String]
    ) {
        self.roleSlugs = roleSlugs
        self.organizationIds = organizationIds
    }

    private enum CodingKeys: String, CodingKey {
        case roleSlugs = "role_slugs"
        case organizationIds = "organization_ids"
    }
}
