// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AgentRegistrationClaimCompletedData: Codable, Sendable, Equatable {
    /// Distinguishes the agent registration claim object.
    public let object: String
    /// Unique identifier of the agent registration claim.
    public let id: String
    /// The ID of the agent registration.
    public let agentRegistrationId: String
    /// The ID of the claim attempt that completed the claim.
    public let completedByAttemptId: String
    /// The user who completed the claim.
    public let claimedBy: AgentRegistrationClaimCompletedDataClaimedBy
    /// The timestamp when the claim was completed.
    public let completedAt: String
    /// The timestamp when the claim was created.
    public let createdAt: String
    /// The timestamp when the claim was last updated.
    public let updatedAt: String

    public init(
        object: String,
        id: String,
        agentRegistrationId: String,
        completedByAttemptId: String,
        claimedBy: AgentRegistrationClaimCompletedDataClaimedBy,
        completedAt: String,
        createdAt: String,
        updatedAt: String
    ) {
        self.object = object
        self.id = id
        self.agentRegistrationId = agentRegistrationId
        self.completedByAttemptId = completedByAttemptId
        self.claimedBy = claimedBy
        self.completedAt = completedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case agentRegistrationId = "agent_registration_id"
        case completedByAttemptId = "completed_by_attempt_id"
        case claimedBy = "claimed_by"
        case completedAt = "completed_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
