// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AgentInstanceSessionCreatedData: Codable, Sendable, Equatable {
    /// Distinguishes the agent instance session object.
    public let object: String
    /// Unique identifier of the agent instance session.
    public let id: String
    /// The agent instance the session belongs to.
    public let agentInstanceId: String
    /// The organization the owning agent instance belongs to.
    public let organizationId: String
    /// Timestamp when the session expires.
    public let expiresAt: String
    /// Timestamp when the session was revoked; `null` if it has not been revoked.
    public let revokedAt: String?
    /// The timestamp when the session was created.
    public let createdAt: String
    /// The timestamp when the session was last updated.
    public let updatedAt: String
    /// The permissions granted to the session at mint time.
    public let permissionSlugs: [String]

    public init(
        object: String,
        id: String,
        agentInstanceId: String,
        organizationId: String,
        expiresAt: String,
        createdAt: String,
        updatedAt: String,
        permissionSlugs: [String],
        revokedAt: String? = nil
    ) {
        self.object = object
        self.id = id
        self.agentInstanceId = agentInstanceId
        self.organizationId = organizationId
        self.expiresAt = expiresAt
        self.revokedAt = revokedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.permissionSlugs = permissionSlugs
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case agentInstanceId = "agent_instance_id"
        case organizationId = "organization_id"
        case expiresAt = "expires_at"
        case revokedAt = "revoked_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case permissionSlugs = "permission_slugs"
    }
}
