// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ApiKeyInstallation: Codable, Sendable, Equatable {
    /// The API key secret to store for the tenant.
    public let secret: String
    /// The User identifier the API key is installed for.
    public let userId: String
    /// An Organization identifier to scope the installation to a specific organization.
    public let organizationId: String?

    public init(
        secret: String,
        userId: String,
        organizationId: String? = nil
    ) {
        self.secret = secret
        self.userId = userId
        self.organizationId = organizationId
    }

    private enum CodingKeys: String, CodingKey {
        case secret
        case userId = "user_id"
        case organizationId = "organization_id"
    }
}
