// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct ApiKeyRevokedData: Codable, Sendable, Equatable {
    /// Distinguishes the API key object.
    public let object: String
    /// Unique identifier of the API key.
    public let id: String
    /// The owner of the API key.
    public let owner: ApiKeyRevokedDataOwner
    /// The name of the API key.
    public let name: String
    /// The obfuscated value of the API key.
    public let obfuscatedValue: String
    /// The timestamp when the API key was last used.
    public let lastUsedAt: String?
    /// Timestamp when the API Key expires. Null means the key does not expire.
    public let expiresAt: Date?
    /// The permissions granted to the API key.
    public let permissions: [String]
    /// The timestamp when the API key was created.
    public let createdAt: String
    /// The timestamp when the API key was last updated.
    public let updatedAt: String

    public init(
        object: String,
        id: String,
        owner: ApiKeyRevokedDataOwner,
        name: String,
        obfuscatedValue: String,
        permissions: [String],
        createdAt: String,
        updatedAt: String,
        lastUsedAt: String? = nil,
        expiresAt: Date? = nil
    ) {
        self.object = object
        self.id = id
        self.owner = owner
        self.name = name
        self.obfuscatedValue = obfuscatedValue
        self.lastUsedAt = lastUsedAt
        self.expiresAt = expiresAt
        self.permissions = permissions
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case owner
        case name
        case obfuscatedValue = "obfuscated_value"
        case lastUsedAt = "last_used_at"
        case expiresAt = "expires_at"
        case permissions
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
