// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuditLogConfiguration: Codable, Sendable, Equatable {
    /// Unique identifier of the Organization.
    public let organizationId: String
    /// The number of days Audit Log events will be retained before being permanently deleted.
    public let retentionPeriodInDays: Int
    /// The current state of the audit log configuration for the organization.
    public let state: AuditLogConfigurationState
    /// The Audit Log Stream currently configured for the organization, if any.
    public let logStream: AuditLogConfigurationLogStream?

    public init(
        organizationId: String,
        retentionPeriodInDays: Int,
        state: AuditLogConfigurationState,
        logStream: AuditLogConfigurationLogStream? = nil
    ) {
        self.organizationId = organizationId
        self.retentionPeriodInDays = retentionPeriodInDays
        self.state = state
        self.logStream = logStream
    }

    private enum CodingKeys: String, CodingKey {
        case organizationId = "organization_id"
        case retentionPeriodInDays = "retention_period_in_days"
        case state
        case logStream = "log_stream"
    }
}
