// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuditLogExport: Codable, Sendable, Equatable {
    /// Distinguishes the Audit Log Export object.
    public let object: String
    /// The unique ID of the Audit Log Export.
    public let id: String
    /// The state of the export. Possible values: pending, ready, error, expired.
    public let state: AuditLogExportState
    /// A URL to the CSV file. Only defined when the Audit Log Export is ready.
    public let url: String?
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        state: AuditLogExportState,
        createdAt: Date,
        updatedAt: Date,
        url: String? = nil
    ) {
        self.object = object
        self.id = id
        self.state = state
        self.url = url
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case state
        case url
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
