// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuditLogEventTarget: Codable, Sendable, Equatable {
    /// Target identifier.
    public let id: String
    /// Target type.
    public let type: String
    /// Optional target name.
    public let name: String?
    /// Additional data associated with the event or entity.
    public let metadata: [String: AnyCodable]?

    public init(
        id: String,
        type: String,
        name: String? = nil,
        metadata: [String: AnyCodable]? = nil
    ) {
        self.id = id
        self.type = type
        self.name = name
        self.metadata = metadata
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case type
        case name
        case metadata
    }
}
