// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuditLogSchemaTarget: Codable, Sendable, Equatable {
    /// The type of the target resource.
    public let type: String
    /// Additional data associated with the event or entity.
    public let metadata: [String: AnyCodable]?

    public init(
        type: String,
        metadata: [String: AnyCodable]? = nil
    ) {
        self.type = type
        self.metadata = metadata
    }

    private enum CodingKeys: String, CodingKey {
        case type
        case metadata
    }
}
