// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuditLogsRetention: Codable, Sendable, Equatable {
    /// The number of days Audit Log events will be retained before being permanently deleted. Valid values are 30 and 365.
    public let retentionPeriodInDays: Int?

    public init(
        retentionPeriodInDays: Int? = nil
    ) {
        self.retentionPeriodInDays = retentionPeriodInDays
    }

    private enum CodingKeys: String, CodingKey {
        case retentionPeriodInDays = "retention_period_in_days"
    }
}
