// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuditLogAction: Codable, Sendable, Equatable {
    /// Distinguishes the Audit Log Action object.
    public let object: String
    /// Identifier of what action was taken.
    public let name: String
    /// The schema associated with the action.
    public let schema: AuditLogSchema
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        name: String,
        schema: AuditLogSchema,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.object = object
        self.name = name
        self.schema = schema
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case name
        case schema
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
