// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuthorizationResource: Codable, Sendable, Equatable {
    /// Distinguishes the Resource object.
    public let object: String
    /// A human-readable name for the Resource.
    public let name: String
    /// An optional description of the Resource.
    public let description: String?
    /// The ID of the organization that owns the resource.
    public let organizationId: String
    /// The ID of the parent resource, if this resource is nested.
    public let parentResourceId: String?
    /// The unique ID of the Resource.
    public let id: String
    /// An identifier you provide to reference the resource in your system.
    public let externalId: String
    /// The slug of the resource type this resource belongs to.
    public let resourceTypeSlug: String
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        name: String,
        organizationId: String,
        id: String,
        externalId: String,
        resourceTypeSlug: String,
        createdAt: Date,
        updatedAt: Date,
        description: String? = nil,
        parentResourceId: String? = nil
    ) {
        self.object = object
        self.name = name
        self.description = description
        self.organizationId = organizationId
        self.parentResourceId = parentResourceId
        self.id = id
        self.externalId = externalId
        self.resourceTypeSlug = resourceTypeSlug
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case name
        case description
        case organizationId = "organization_id"
        case parentResourceId = "parent_resource_id"
        case id
        case externalId = "external_id"
        case resourceTypeSlug = "resource_type_slug"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
