// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct AuthenticationRadarRiskDetectedData: Codable, Sendable, Equatable {
    /// The authentication method used.
    public let authMethod: String
    public let action: AuthenticationRadarRiskDetectedDataAction
    /// The control action taken for the detected risk.
    public let control: String?
    /// The type of blocklist that triggered the risk detection.
    public let blocklistType: String?
    /// The IP address of the request.
    public let ipAddress: String?
    /// The user agent of the request.
    public let userAgent: String?
    /// The ID of the user.
    public let userId: String
    /// The email address of the user.
    public let email: String

    public init(
        authMethod: String,
        action: AuthenticationRadarRiskDetectedDataAction,
        userId: String,
        email: String,
        control: String? = nil,
        blocklistType: String? = nil,
        ipAddress: String? = nil,
        userAgent: String? = nil
    ) {
        self.authMethod = authMethod
        self.action = action
        self.control = control
        self.blocklistType = blocklistType
        self.ipAddress = ipAddress
        self.userAgent = userAgent
        self.userId = userId
        self.email = email
    }

    private enum CodingKeys: String, CodingKey {
        case authMethod = "auth_method"
        case action
        case control
        case blocklistType = "blocklist_type"
        case ipAddress = "ip_address"
        case userAgent = "user_agent"
        case userId = "user_id"
        case email
    }
}
