// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuthenticationChallengesVerifyRequest: Codable, Sendable, Equatable {
    /// The one-time code to verify.
    public let code: String

    public init(
        code: String
    ) {
        self.code = code
    }

    private enum CodingKeys: String, CodingKey {
        case code
    }
}
