// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct AuthMethodMismatchError: Codable, Sendable, Equatable {
    /// Error code indicating the endpoint does not match the installation auth method.
    public let code: String
    /// A human-readable explanation of the mismatch.
    public let message: String

    public init(
        code: String,
        message: String
    ) {
        self.code = code
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case code
        case message
    }
}
