// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CheckAuthorization: Codable, Sendable, Equatable {
    /// The slug of the permission to check.
    public let permissionSlug: String
    /// The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`.
    public let resourceId: String?
    /// The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`.
    public let resourceExternalId: String?
    /// The slug of the resource type. Required with `resource_external_id`. Mutually exclusive with `resource_id`.
    public let resourceTypeSlug: String?

    public init(
        permissionSlug: String,
        resourceId: String? = nil,
        resourceExternalId: String? = nil,
        resourceTypeSlug: String? = nil
    ) {
        self.permissionSlug = permissionSlug
        self.resourceId = resourceId
        self.resourceExternalId = resourceExternalId
        self.resourceTypeSlug = resourceTypeSlug
    }

    private enum CodingKeys: String, CodingKey {
        case permissionSlug = "permission_slug"
        case resourceId = "resource_id"
        case resourceExternalId = "resource_external_id"
        case resourceTypeSlug = "resource_type_slug"
    }
}
