// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ClaimViewResponseOrganization: Codable, Sendable, Equatable {
    /// The organization ID.
    public let id: String
    /// The organization name.
    public let name: String

    public init(
        id: String,
        name: String
    ) {
        self.id = id
        self.name = name
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
    }
}
