// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ClaimViewResponse: Codable, Sendable, Equatable {
    /// The agent registration ID.
    public let id: String
    /// Current status of the agent registration.
    public let status: ClaimViewResponseStatus
    /// The user code the agent needs to complete the claim.
    public let userCode: String
    /// Organizations the user belongs to, offered as placement choices.
    public let organizations: [ClaimViewResponseOrganization]

    public init(
        id: String,
        status: ClaimViewResponseStatus,
        userCode: String,
        organizations: [ClaimViewResponseOrganization]
    ) {
        self.id = id
        self.status = status
        self.userCode = userCode
        self.organizations = organizations
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case status
        case userCode = "user_code"
        case organizations
    }
}
