// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ClientApiTokenResponse: Codable, Sendable, Equatable {
    /// The Client API token.
    public let token: String

    public init(
        token: String
    ) {
        self.token = token
    }

    private enum CodingKeys: String, CodingKey {
        case token
    }
}
