// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ConfigureDataIntegrationBody: Codable, Sendable, Equatable {
    /// Whether the provider is enabled for the organization.
    public let enabled: Bool?
    /// The OAuth scopes to request for the organization. Pass `null` to inherit the provider scopes.
    public let scopes: [String]?
    /// The OAuth client ID of the organization's own application. Must be provided together with `client_secret`, and only for providers whose credentials are supplied by the organization.
    public let clientId: String?
    /// The OAuth client secret of the organization's own application. Must be provided together with `client_id`.
    public let clientSecret: String?
    /// Provider-specific config values to set for the organization, keyed by config field. Only fields the provider declares are accepted, and each value must match that field's pattern. Accepted only for providers whose credentials are organization-managed; for shared or custom credential providers, config belongs on the integration itself (via the data-integrations API) and supplying it here is rejected.
    public let config: [String: String]?

    public init(
        enabled: Bool? = nil,
        scopes: [String]? = nil,
        clientId: String? = nil,
        clientSecret: String? = nil,
        config: [String: String]? = nil
    ) {
        self.enabled = enabled
        self.scopes = scopes
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.config = config
    }

    private enum CodingKeys: String, CodingKey {
        case enabled
        case scopes
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case config
    }
}
