// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The connection with the renewed certificate.
public struct ConnectionSAMLCertificateRenewedDataConnection: Codable, Sendable, Equatable {
    /// Unique identifier of the connection.
    public let id: String
    /// The ID of the organization the connection belongs to.
    public let organizationId: String?

    public init(
        id: String,
        organizationId: String? = nil
    ) {
        self.id = id
        self.organizationId = organizationId
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case organizationId = "organization_id"
    }
}
