// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct ConnectionDeactivatedData: Codable, Sendable, Equatable {
    /// Distinguishes the connection object.
    public let object: String
    /// Unique identifier of the connection.
    public let id: String
    /// The current state of the connection.
    public let state: ConnectionDeactivatedDataState
    /// The name of the connection.
    public let name: String
    /// The type of the connection.
    public let connectionType: ConnectionDeactivatedDataConnectionType
    /// The ID of the organization the connection belongs to.
    public let organizationId: String?
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date
    /// The external key of the connection.
    public let externalKey: String
    /// Deprecated. Use state instead.
    public let status: ConnectionDeactivatedDataStatus
    /// The domains associated with the connection.
    public let domains: [ConnectionDeactivatedDataDomain]

    public init(
        object: String,
        id: String,
        state: ConnectionDeactivatedDataState,
        name: String,
        connectionType: ConnectionDeactivatedDataConnectionType,
        createdAt: Date,
        updatedAt: Date,
        externalKey: String,
        status: ConnectionDeactivatedDataStatus,
        domains: [ConnectionDeactivatedDataDomain],
        organizationId: String? = nil
    ) {
        self.object = object
        self.id = id
        self.state = state
        self.name = name
        self.connectionType = connectionType
        self.organizationId = organizationId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.externalKey = externalKey
        self.status = status
        self.domains = domains
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case state
        case name
        case connectionType = "connection_type"
        case organizationId = "organization_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case externalKey = "external_key"
        case status
        case domains
    }
}
