// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ConnectionDeactivatedDataDomain: Codable, Sendable, Equatable {
    /// Distinguishes the connection domain object.
    public let object: String
    /// Unique identifier of the connection domain.
    public let id: String
    /// The domain value.
    public let domain: String

    public init(
        object: String,
        id: String,
        domain: String
    ) {
        self.object = object
        self.id = id
        self.domain = domain
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case domain
    }
}
