// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct Connection: Codable, Sendable, Equatable {
    /// Distinguishes the Connection object.
    public let object: String
    /// Unique identifier for the Connection.
    public let id: String
    /// Unique identifier for the Organization in which the Connection resides.
    public let organizationId: String?
    /// The type of the SSO Connection used to authenticate the user. The Connection type may be used to dynamically generate authorization URLs.
    public let connectionType: ConnectionType
    /// A human-readable name for the Connection. This will most commonly be the organization's name.
    public let name: String
    /// Indicates whether a Connection is able to authenticate users.
    public let state: ConnectionState
    /// Deprecated. Use `state` instead.
    @available(*, deprecated)
    public let status: ConnectionStatus
    /// List of Organization Domains.
    public let domains: [ConnectionDomain]
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        connectionType: ConnectionType,
        name: String,
        state: ConnectionState,
        status: ConnectionStatus,
        domains: [ConnectionDomain],
        createdAt: Date,
        updatedAt: Date,
        organizationId: String? = nil
    ) {
        self.object = object
        self.id = id
        self.organizationId = organizationId
        self.connectionType = connectionType
        self.name = name
        self.state = state
        self.status = status
        self.domains = domains
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case organizationId = "organization_id"
        case connectionType = "connection_type"
        case name
        case state
        case status
        case domains
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
