// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The renewed SAML certificate details.
public struct ConnectionSAMLCertificateRenewedDataCertificate: Codable, Sendable, Equatable {
    /// The type of the SAML certificate.
    public let certificateType: ConnectionSAMLCertificateRenewedDataCertificateCertificateType
    /// An ISO 8601 timestamp.
    public let expiryDate: Date

    public init(
        certificateType: ConnectionSAMLCertificateRenewedDataCertificateCertificateType,
        expiryDate: Date
    ) {
        self.certificateType = certificateType
        self.expiryDate = expiryDate
    }

    private enum CodingKeys: String, CodingKey {
        case certificateType = "certificate_type"
        case expiryDate = "expiry_date"
    }
}
