// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ConnectedAccountDto: Codable, Sendable, Equatable {
    /// The OAuth access token for the connected account.
    public let accessToken: String?
    /// The OAuth refresh token for the connected account.
    public let refreshToken: String?
    /// The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
    public let expiresAt: Date?
    /// The OAuth scopes granted for this connection.
    public let scopes: [String]?
    /// Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
    public let state: ConnectedAccountState?

    public init(
        accessToken: String? = nil,
        refreshToken: String? = nil,
        expiresAt: Date? = nil,
        scopes: [String]? = nil,
        state: ConnectedAccountState? = nil
    ) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.expiresAt = expiresAt
        self.scopes = scopes
        self.state = state
    }

    private enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
        case expiresAt = "expires_at"
        case scopes
        case state
    }
}
