// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateM2MApplication: Codable, Sendable, Equatable {
    /// The name of the application.
    public let name: String
    /// The type of application to create.
    public let applicationType: String
    /// A description for the application.
    public let description: String?
    /// The OAuth scopes granted to the application.
    public let scopes: [String]?
    /// The organization ID this application belongs to.
    public let organizationId: String

    public init(
        name: String,
        applicationType: String,
        organizationId: String,
        description: String? = nil,
        scopes: [String]? = nil
    ) {
        self.name = name
        self.applicationType = applicationType
        self.description = description
        self.scopes = scopes
        self.organizationId = organizationId
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case applicationType = "application_type"
        case description
        case scopes
        case organizationId = "organization_id"
    }
}
