// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateUserOrganizationMembership: Codable, Sendable, Equatable {
    /// The ID of the [user](https://workos.com/docs/reference/authkit/user).
    public let userId: String
    /// The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
    public let organizationId: String
    /// A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`.
    public let roleSlug: String?
    /// An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`.
    public let roleSlugs: [String]?

    public init(
        userId: String,
        organizationId: String,
        roleSlug: String? = nil,
        roleSlugs: [String]? = nil
    ) {
        self.userId = userId
        self.organizationId = organizationId
        self.roleSlug = roleSlug
        self.roleSlugs = roleSlugs
    }

    private enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case organizationId = "organization_id"
        case roleSlug = "role_slug"
        case roleSlugs = "role_slugs"
    }
}
