// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateObjectRequest: Codable, Sendable, Equatable {
    /// Map of values used to determine the encryption key.
    public let keyContext: [String: String]
    /// Unique name for the object.
    public let name: String
    /// Plaintext data to encrypt and store.
    public let value: String

    public init(
        keyContext: [String: String],
        name: String,
        value: String
    ) {
        self.keyContext = keyContext
        self.name = name
        self.value = value
    }

    private enum CodingKeys: String, CodingKey {
        case keyContext = "key_context"
        case name
        case value
    }
}
