// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateWebhookEndpoint: Codable, Sendable, Equatable {
    /// The HTTPS URL where webhooks will be sent.
    public let endpointUrl: String
    /// The events that the Webhook Endpoint is subscribed to.
    public let events: [CreateWebhookEndpointEvents]

    public init(
        endpointUrl: String,
        events: [CreateWebhookEndpointEvents]
    ) {
        self.endpointUrl = endpointUrl
        self.events = events
    }

    private enum CodingKeys: String, CodingKey {
        case endpointUrl = "endpoint_url"
        case events
    }
}
