// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateConnectionKeyPair: Codable, Sendable, Equatable {
    /// The PEM-encoded private key.
    public let key: String
    /// The PEM-encoded X.509 certificate for the key.
    public let cert: String

    public init(
        key: String,
        cert: String
    ) {
        self.key = key
        self.cert = cert
    }

    private enum CodingKeys: String, CodingKey {
        case key
        case cert
    }
}
