// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateOrganizationRole: Codable, Sendable, Equatable {
    /// A unique identifier for the role within the organization. When provided, must begin with 'org-' and contain only lowercase letters, numbers, hyphens, and underscores. When omitted, a slug is auto-generated from the role name and a random suffix.
    public let slug: String?
    /// A descriptive name for the role.
    public let name: String
    /// An optional description of the role's purpose.
    public let description: String?
    /// The slug of the resource type the role is scoped to.
    public let resourceTypeSlug: String?

    public init(
        name: String,
        slug: String? = nil,
        description: String? = nil,
        resourceTypeSlug: String? = nil
    ) {
        self.slug = slug
        self.name = name
        self.description = description
        self.resourceTypeSlug = resourceTypeSlug
    }

    private enum CodingKeys: String, CodingKey {
        case slug
        case name
        case description
        case resourceTypeSlug = "resource_type_slug"
    }
}
