// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateConnectedAccount: Codable, Sendable, Equatable {
    /// The OAuth access token for the connected account.
    public let accessToken: String?
    /// The OAuth refresh token for the connected account.
    public let refreshToken: String?
    /// The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
    public let expiresAt: Date?
    /// The OAuth scopes granted for this connection.
    public let scopes: [String]?
    /// Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
    public let state: CreateConnectedAccountState?
    /// Set to `add` to create another connected account. Omit this field for permanent compatibility behavior. Creating an additional connection is not yet available: until it is, `add` succeeds only when the owner has no connection for this integration, which creates the compatibility connection, and otherwise returns 404 `multiple_connections_unavailable`.
    public let connectionIntent: String?

    public init(
        accessToken: String? = nil,
        refreshToken: String? = nil,
        expiresAt: Date? = nil,
        scopes: [String]? = nil,
        state: CreateConnectedAccountState? = nil,
        connectionIntent: String? = nil
    ) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.expiresAt = expiresAt
        self.scopes = scopes
        self.state = state
        self.connectionIntent = connectionIntent
    }

    private enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
        case expiresAt = "expires_at"
        case scopes
        case state
        case connectionIntent = "connection_intent"
    }
}
