// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateUser: Codable, Sendable, Equatable {
    /// The email address of the user.
    public let email: String
    /// The first name of the user.
    public let firstName: String?
    /// The last name of the user.
    public let lastName: String?
    /// The user's full name.
    public let name: String?
    /// Whether the user's email has been verified.
    public let emailVerified: Bool?
    /// Object containing metadata key/value pairs associated with the user.
    public let metadata: [String: String]?
    /// The external ID of the user.
    public let externalId: String?
    /// The IP address of the user's request.
    public let ipAddress: String?
    /// The user agent string from the user's request.
    public let userAgent: String?
    /// An optional Radar signals ID to correlate client-side signals with this request.
    public let signalsId: String?
    /// The password to set for the user. Mutually exclusive with `password_hash` and `password_hash_type`.
    public let password: String?
    /// The hashed password to set for the user. Required with `password_hash_type`. Mutually exclusive with `password`.
    public let passwordHash: String?
    /// The algorithm originally used to hash the password, used when providing a `password_hash`. Required with `password_hash`. Mutually exclusive with `password`.
    public let passwordHashType: CreateUserPasswordHashType?

    public init(
        email: String,
        firstName: String? = nil,
        lastName: String? = nil,
        name: String? = nil,
        emailVerified: Bool? = nil,
        metadata: [String: String]? = nil,
        externalId: String? = nil,
        ipAddress: String? = nil,
        userAgent: String? = nil,
        signalsId: String? = nil,
        password: String? = nil,
        passwordHash: String? = nil,
        passwordHashType: CreateUserPasswordHashType? = nil
    ) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.name = name
        self.emailVerified = emailVerified
        self.metadata = metadata
        self.externalId = externalId
        self.ipAddress = ipAddress
        self.userAgent = userAgent
        self.signalsId = signalsId
        self.password = password
        self.passwordHash = passwordHash
        self.passwordHashType = passwordHashType
    }

    private enum CodingKeys: String, CodingKey {
        case email
        case firstName = "first_name"
        case lastName = "last_name"
        case name
        case emailVerified = "email_verified"
        case metadata
        case externalId = "external_id"
        case ipAddress = "ip_address"
        case userAgent = "user_agent"
        case signalsId = "signals_id"
        case password
        case passwordHash = "password_hash"
        case passwordHashType = "password_hash_type"
    }
}
