// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateOrganizationApiKey: Codable, Sendable, Equatable {
    /// The name for the API key.
    public let name: String
    /// The permission slugs to assign to the API key.
    public let permissions: [String]?
    /// The timestamp when the API key should expire. Must be a future timestamp. If omitted, the key does not expire.
    public let expiresAt: Date?

    public init(
        name: String,
        permissions: [String]? = nil,
        expiresAt: Date? = nil
    ) {
        self.name = name
        self.permissions = permissions
        self.expiresAt = expiresAt
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case permissions
        case expiresAt = "expires_at"
    }
}
