// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateConnection: Codable, Sendable, Equatable {
    /// Unique identifier for the Organization in which the Connection resides.
    public let organizationId: String
    /// A human-readable name for the Connection. This will most commonly be the organization's name.
    public let name: String?
    /// The customer-owned identifier for the Connection.
    public let externalId: String?
    /// The type of the Connection. Only SAML and OIDC connection types may be created. When omitted, the type is inferred from the provided options.
    public let connectionType: String?
    /// How IdP attributes or claims map onto WorkOS profile fields. Provided fields override the defaults for the connection type.
    public let attributeMaps: CreateConnectionAttributeMaps?
    /// Protocol configuration for SAML connections. Mutually exclusive with `oidc_options`.
    public let samlOptions: CreateConnectionSAMLOptions?
    /// Protocol configuration for OIDC connections. Mutually exclusive with `saml_options`.
    public let oidcOptions: CreateConnectionOidcOptions?

    public init(
        organizationId: String,
        name: String? = nil,
        externalId: String? = nil,
        connectionType: String? = nil,
        attributeMaps: CreateConnectionAttributeMaps? = nil,
        samlOptions: CreateConnectionSAMLOptions? = nil,
        oidcOptions: CreateConnectionOidcOptions? = nil
    ) {
        self.organizationId = organizationId
        self.name = name
        self.externalId = externalId
        self.connectionType = connectionType
        self.attributeMaps = attributeMaps
        self.samlOptions = samlOptions
        self.oidcOptions = oidcOptions
    }

    private enum CodingKeys: String, CodingKey {
        case organizationId = "organization_id"
        case name
        case externalId = "external_id"
        case connectionType = "connection_type"
        case attributeMaps = "attribute_maps"
        case samlOptions = "saml_options"
        case oidcOptions = "oidc_options"
    }
}
