// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CreateCorsOrigin: Codable, Sendable, Equatable {
    /// The origin URL to allow for CORS requests.
    public let origin: String

    public init(
        origin: String
    ) {
        self.origin = origin
    }

    private enum CodingKeys: String, CodingKey {
        case origin
    }
}
