// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct CustomProviderDefinition: Codable, Sendable, Equatable {
    /// A descriptive name for the custom provider.
    public let name: String
    /// The provider's OAuth authorization endpoint.
    public let authorizationUrl: String
    /// The provider's OAuth token endpoint.
    public let tokenUrl: String
    /// The endpoint used to refresh tokens, if different from the token endpoint.
    public let refreshTokenUrl: String?
    /// Whether PKCE is used during the authorization code flow. Defaults to `true`.
    public let pkceEnabled: Bool?
    /// The separator used to join requested scopes. Defaults to a space.
    public let requestScopeSeparator: String?
    /// Whether at least one scope must be selected when connecting an account. Defaults to `false`.
    public let scopesRequired: Bool?
    /// Whether a client secret is required for this provider. Defaults to `true`.
    public let clientSecretRequired: Bool?
    /// Additional static query parameters appended to the authorization request.
    public let additionalAuthorizationParameters: [String: String]?
    /// The Content-Type used when exchanging the token request.
    public let tokenBodyContentType: String?
    /// How client credentials are sent when exchanging authorization codes and refreshing tokens.
    public let authenticateVia: CustomProviderDefinitionAuthenticateVia?

    public init(
        name: String,
        authorizationUrl: String,
        tokenUrl: String,
        refreshTokenUrl: String? = nil,
        pkceEnabled: Bool? = nil,
        requestScopeSeparator: String? = nil,
        scopesRequired: Bool? = nil,
        clientSecretRequired: Bool? = nil,
        additionalAuthorizationParameters: [String: String]? = nil,
        tokenBodyContentType: String? = nil,
        authenticateVia: CustomProviderDefinitionAuthenticateVia? = nil
    ) {
        self.name = name
        self.authorizationUrl = authorizationUrl
        self.tokenUrl = tokenUrl
        self.refreshTokenUrl = refreshTokenUrl
        self.pkceEnabled = pkceEnabled
        self.requestScopeSeparator = requestScopeSeparator
        self.scopesRequired = scopesRequired
        self.clientSecretRequired = clientSecretRequired
        self.additionalAuthorizationParameters = additionalAuthorizationParameters
        self.tokenBodyContentType = tokenBodyContentType
        self.authenticateVia = authenticateVia
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case authorizationUrl = "authorization_url"
        case tokenUrl = "token_url"
        case refreshTokenUrl = "refresh_token_url"
        case pkceEnabled = "pkce_enabled"
        case requestScopeSeparator = "request_scope_separator"
        case scopesRequired = "scopes_required"
        case clientSecretRequired = "client_secret_required"
        case additionalAuthorizationParameters = "additional_authorization_parameters"
        case tokenBodyContentType = "token_body_content_type"
        case authenticateVia = "authenticate_via"
    }
}
