// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegrationInstallation: Codable, Sendable, Equatable {
    /// Unique identifier of the installation.
    public let id: String
    /// The User the API key was installed for.
    public let userId: String
    /// The Organization the installation is scoped to, or null when unscoped.
    public let organizationId: String?
    /// The last four characters of the stored API key. The full key is never returned.
    public let apiKeyLast4: String?

    public init(
        id: String,
        userId: String,
        organizationId: String? = nil,
        apiKeyLast4: String? = nil
    ) {
        self.id = id
        self.userId = userId
        self.organizationId = organizationId
        self.apiKeyLast4 = apiKeyLast4
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case organizationId = "organization_id"
        case apiKeyLast4 = "api_key_last_4"
    }
}
