// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegrationsListResponseDataConnectedAccount: Codable, Sendable, Equatable {
    /// Distinguishes the connected account object.
    public let object: String
    /// The unique identifier of the connected account.
    public let id: String
    /// Whether this row is the compatibility connection visible to undeclared clients or a standard peer for plural-aware clients. The role does not indicate preference or creation order.
    public let connectionRole: DataIntegrationsListResponseDataConnectedAccountConnectionRole
    /// A best-effort identifier for the provider account this connection points at. It is correlation metadata, not the connection identifier or a selector.
    public let accountIdentifier: String?
    /// A mutable, non-unique display name for the provider account connection.
    public let accountDisplayName: String?
    /// The [User](https://workos.com/docs/reference/authkit/user) identifier associated with this connection.
    public let userId: String?
    /// The [Organization](https://workos.com/docs/reference/organization) identifier associated with this connection, or `null` if not scoped to an organization.
    public let organizationId: String?
    /// The OAuth scopes granted for this connection.
    public let scopes: [String]
    /// The authentication method used for this connection (`oauth`, `api_key`, or `client_credentials`). Defaults to `oauth` if absent.
    public let authMethod: DataIntegrationsListResponseDataConnectedAccountAuthMethod?
    /// The last four characters of the API key, or `null` for OAuth connections.
    public let apiKeyLast4: String?
    /// The client ID supplied for this connection. Only present when `auth_method` is `client_credentials`.
    public let clientId: String?
    /// The last four characters of the client secret supplied for this connection, or `null` when it can't be read. Only present when `auth_method` is `client_credentials`.
    public let clientSecretLast4: String?
    /// The connection-level configuration values stored for this connection — the fields the provider declares at `installation` scope, excluding any it declares as secret. Only present when `auth_method` is `client_credentials`.
    public let config: [String: String]?
    /// The state of the connected account:
    /// - `connected`: The connection is active and tokens are valid.
    /// - `needs_reauthorization`: The user needs to reauthorize the connection, typically because required scopes have changed.
    /// - `disconnected`: The connection has been disconnected.
    public let state: DataIntegrationsListResponseDataConnectedAccountState
    /// The timestamp when the connection was created.
    public let createdAt: String
    /// The timestamp when the connection was last updated.
    public let updatedAt: String
    /// Use `user_id` instead.
    @available(*, deprecated)
    public let userlandUserId: String?

    public init(
        object: String,
        id: String,
        connectionRole: DataIntegrationsListResponseDataConnectedAccountConnectionRole,
        scopes: [String],
        state: DataIntegrationsListResponseDataConnectedAccountState,
        createdAt: String,
        updatedAt: String,
        accountIdentifier: String? = nil,
        accountDisplayName: String? = nil,
        userId: String? = nil,
        organizationId: String? = nil,
        authMethod: DataIntegrationsListResponseDataConnectedAccountAuthMethod? = nil,
        apiKeyLast4: String? = nil,
        clientId: String? = nil,
        clientSecretLast4: String? = nil,
        config: [String: String]? = nil,
        userlandUserId: String? = nil
    ) {
        self.object = object
        self.id = id
        self.connectionRole = connectionRole
        self.accountIdentifier = accountIdentifier
        self.accountDisplayName = accountDisplayName
        self.userId = userId
        self.organizationId = organizationId
        self.scopes = scopes
        self.authMethod = authMethod
        self.apiKeyLast4 = apiKeyLast4
        self.clientId = clientId
        self.clientSecretLast4 = clientSecretLast4
        self.config = config
        self.state = state
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.userlandUserId = userlandUserId
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case connectionRole = "connection_role"
        case accountIdentifier = "account_identifier"
        case accountDisplayName = "account_display_name"
        case userId = "user_id"
        case organizationId = "organization_id"
        case scopes
        case authMethod = "auth_method"
        case apiKeyLast4 = "api_key_last_4"
        case clientId = "client_id"
        case clientSecretLast4 = "client_secret_last_4"
        case config
        case state
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case userlandUserId
    }
}
