// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegration: Codable, Sendable, Equatable {
    /// Distinguishes the Data Integration object.
    public let object: String
    /// Unique identifier of the Data Integration.
    public let id: String
    /// The provider slug for this Data Integration.
    public let slug: String
    /// The integration type derived from the provider.
    public let integrationType: String
    /// An optional description of the Data Integration.
    public let description: String?
    /// Whether the Data Integration is enabled.
    public let enabled: Bool
    /// The state of the Data Integration.
    public let state: DataIntegrationState
    /// The OAuth scopes configured for the Data Integration. `null` when the provider's configured scopes are used.
    public let scopes: [String]?
    /// The OAuth redirect URI to register with the provider when configuring the custom application.
    public let redirectUri: String
    /// The credentials configured for the Data Integration.
    public let credentials: DataIntegrationCredential
    /// The OAuth definition when this is a custom provider; `null` for built-in providers.
    public let customProvider: DataIntegrationCustomProvider?
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        slug: String,
        integrationType: String,
        enabled: Bool,
        state: DataIntegrationState,
        redirectUri: String,
        credentials: DataIntegrationCredential,
        createdAt: Date,
        updatedAt: Date,
        description: String? = nil,
        scopes: [String]? = nil,
        customProvider: DataIntegrationCustomProvider? = nil
    ) {
        self.object = object
        self.id = id
        self.slug = slug
        self.integrationType = integrationType
        self.description = description
        self.enabled = enabled
        self.state = state
        self.scopes = scopes
        self.redirectUri = redirectUri
        self.credentials = credentials
        self.customProvider = customProvider
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case slug
        case integrationType = "integration_type"
        case description
        case enabled
        case state
        case scopes
        case redirectUri = "redirect_uri"
        case credentials
        case customProvider = "custom_provider"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
