// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegrationsListResponseData: Codable, Sendable, Equatable {
    /// Distinguishes the data provider object.
    public let object: String
    /// The unique identifier of the provider.
    public let id: String
    /// The display name of the provider (e.g., "GitHub", "Slack").
    public let name: String
    /// A description of the provider explaining how it will be used, if configured.
    public let description: String?
    /// The slug identifier used in API calls (e.g., `github`, `slack`, `notion`).
    public let slug: String
    /// The type of integration (e.g., `github`, `slack`).
    public let integrationType: String
    /// The type of credentials used by the provider (e.g., `oauth2`).
    public let credentialsType: String
    /// The OAuth scopes configured for this provider, or `null` if none are configured.
    public let scopes: [String]?
    /// The authentication methods supported by this provider (`oauth`, `api_key`, or both). Defaults to `["oauth"]` if absent.
    public let authMethods: [DataIntegrationsListResponseDataAuthMethods]?
    /// Whether the provider is owned by a user or organization.
    public let ownership: DataIntegrationsListResponseDataOwnership
    /// The timestamp when the provider was created.
    public let createdAt: String
    /// The timestamp when the provider was last updated.
    public let updatedAt: String
    /// The user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for this provider, or `null` if the user has not connected.
    public let connectedAccount: DataIntegrationsListResponseDataConnectedAccount?

    public init(
        object: String,
        id: String,
        name: String,
        slug: String,
        integrationType: String,
        credentialsType: String,
        ownership: DataIntegrationsListResponseDataOwnership,
        createdAt: String,
        updatedAt: String,
        description: String? = nil,
        scopes: [String]? = nil,
        authMethods: [DataIntegrationsListResponseDataAuthMethods]? = nil,
        connectedAccount: DataIntegrationsListResponseDataConnectedAccount? = nil
    ) {
        self.object = object
        self.id = id
        self.name = name
        self.description = description
        self.slug = slug
        self.integrationType = integrationType
        self.credentialsType = credentialsType
        self.scopes = scopes
        self.authMethods = authMethods
        self.ownership = ownership
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.connectedAccount = connectedAccount
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case name
        case description
        case slug
        case integrationType = "integration_type"
        case credentialsType = "credentials_type"
        case scopes
        case authMethods = "auth_methods"
        case ownership
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case connectedAccount = "connected_account"
    }
}
