// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegrationsUpsertApiKeyRequest: Codable, Sendable, Equatable {
    /// A [User](https://workos.com/docs/reference/authkit/user) identifier.
    public let userId: String
    /// An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
    public let organizationId: String?
    /// The API key secret to store for this integration.
    public let secret: String

    public init(
        userId: String,
        secret: String,
        organizationId: String? = nil
    ) {
        self.userId = userId
        self.organizationId = organizationId
        self.secret = secret
    }

    private enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case organizationId = "organization_id"
        case secret
    }
}
