// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegrationAccessTokenResponse: Codable, Sendable, Equatable {
    /// Indicates whether the access token is valid and ready for use, or if reauthorization is required.
    public let active: Bool?
    /// The [access token](https://workos.com/docs/reference/pipes/access-token) object, present when `active` is `true`.
    public let accessToken: DataIntegrationAccessTokenResponseAccessToken?
    /// - `"not_installed"`: The user does not have the integration installed.
    /// - `"needs_reauthorization"`: The user needs to reauthorize the integration.
    public let error: DataIntegrationAccessTokenResponseError?

    public init(
        active: Bool? = nil,
        accessToken: DataIntegrationAccessTokenResponseAccessToken? = nil,
        error: DataIntegrationAccessTokenResponseError? = nil
    ) {
        self.active = active
        self.accessToken = accessToken
        self.error = error
    }

    private enum CodingKeys: String, CodingKey {
        case active
        case accessToken = "access_token"
        case error
    }
}
