// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DataIntegrationsCreateClientCredentialsConnectionRequest: Codable, Sendable, Equatable
{
    /// A [User](https://workos.com/docs/reference/authkit/user) identifier.
    public let userId: String
    /// An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. Required when `connection_owner` is `organization`.
    public let organizationId: String?
    /// Whose connection to create or rotate. `user` (the default) addresses the connection owned by `user_id`. `organization` addresses the connection shared by every member of `organization_id`; `user_id` then identifies the member performing the request and must be an active member of the organization.
    public let connectionOwner:
        DataIntegrationsCreateClientCredentialsConnectionRequestConnectionOwner?
    /// The OAuth client ID to store for this integration.
    public let clientId: String
    /// The OAuth client secret to store for this integration.
    public let clientSecret: String
    /// Provider-specific configuration values collected for this installation, keyed by the provider's config field descriptors.
    public let config: [String: String]?
    /// Must be `add`: this endpoint only creates another connection. The first connection for an owner shape fills the compatibility slot; later connections are standard. Creating an additional connection is not yet available: until it is, `add` succeeds only when the owner has no connection for this integration and otherwise returns 404 `multiple_connections_unavailable`.
    public let connectionIntent: String

    public init(
        userId: String,
        clientId: String,
        clientSecret: String,
        connectionIntent: String,
        organizationId: String? = nil,
        connectionOwner: DataIntegrationsCreateClientCredentialsConnectionRequestConnectionOwner? =
            nil,
        config: [String: String]? = nil
    ) {
        self.userId = userId
        self.organizationId = organizationId
        self.connectionOwner = connectionOwner
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.config = config
        self.connectionIntent = connectionIntent
    }

    private enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case organizationId = "organization_id"
        case connectionOwner = "connection_owner"
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case config
        case connectionIntent = "connection_intent"
    }
}
