// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DecryptRequest: Codable, Sendable, Equatable {
    /// Base64-encoded encrypted data key to decrypt.
    public let keys: String

    public init(
        keys: String
    ) {
        self.keys = keys
    }

    private enum CodingKeys: String, CodingKey {
        case keys
    }
}
