// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DeleteObjectResponse: Codable, Sendable, Equatable {
    /// Name of the deleted object.
    public let name: String
    /// Whether the deletion succeeded.
    public let success: Bool

    public init(
        name: String,
        success: Bool
    ) {
        self.name = name
        self.success = success
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case success
    }
}
