// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DirectoryGroup: Codable, Sendable, Equatable {
    /// Distinguishes the Directory Group object.
    public let object: String
    /// Unique identifier for the Directory Group.
    public let id: String
    /// Unique identifier for the group, assigned by the Directory Provider. Different Directory Providers use different ID formats.
    public let idpId: String
    /// The identifier of the Directory the Directory Group belongs to.
    public let directoryId: String
    /// The identifier for the Organization in which the Directory resides.
    public let organizationId: String
    /// The name of the Directory Group.
    public let name: String
    /// The raw attributes received from the directory provider.
    public let rawAttributes: [String: AnyCodable]?
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        idpId: String,
        directoryId: String,
        organizationId: String,
        name: String,
        createdAt: Date,
        updatedAt: Date,
        rawAttributes: [String: AnyCodable]? = nil
    ) {
        self.object = object
        self.id = id
        self.idpId = idpId
        self.directoryId = directoryId
        self.organizationId = organizationId
        self.name = name
        self.rawAttributes = rawAttributes
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case idpId = "idp_id"
        case directoryId = "directory_id"
        case organizationId = "organization_id"
        case name
        case rawAttributes = "raw_attributes"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
