// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Counts of active and inactive directory users.
public struct DirectoryMetadataUser: Codable, Sendable, Equatable {
    /// Count of active directory users.
    public let active: Int
    /// Count of inactive directory users.
    public let inactive: Int

    public init(
        active: Int,
        inactive: Int
    ) {
        self.active = active
        self.inactive = inactive
    }

    private enum CodingKeys: String, CodingKey {
        case active
        case inactive
    }
}
