// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct DsyncGroupUserRemovedData: Codable, Sendable, Equatable {
    /// The ID of the directory.
    public let directoryId: String
    /// The directory user removed from the group.
    public let user: DirectoryUser
    /// The directory group the user was removed from.
    public let group: DirectoryGroup

    public init(
        directoryId: String,
        user: DirectoryUser,
        group: DirectoryGroup
    ) {
        self.directoryId = directoryId
        self.user = user
        self.group = group
    }

    private enum CodingKeys: String, CodingKey {
        case directoryId = "directory_id"
        case user
        case group
    }
}
