// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct DsyncTokenCreatedData: Codable, Sendable, Equatable {
    /// Distinguishes the directory token object.
    public let object: String
    /// Unique identifier of the directory token.
    public let id: String
    /// The ID of the directory the token authenticates to.
    public let directoryId: String
    /// The ID of the organization the directory belongs to.
    public let organizationId: String?
    /// The trailing characters of the bearer token, for identification only. The full token value is never included in events.
    public let tokenSuffix: String
    /// An ISO 8601 timestamp.
    public let createdAt: Date

    public init(
        object: String,
        id: String,
        directoryId: String,
        tokenSuffix: String,
        createdAt: Date,
        organizationId: String? = nil
    ) {
        self.object = object
        self.id = id
        self.directoryId = directoryId
        self.organizationId = organizationId
        self.tokenSuffix = tokenSuffix
        self.createdAt = createdAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case directoryId = "directory_id"
        case organizationId = "organization_id"
        case tokenSuffix = "token_suffix"
        case createdAt = "created_at"
    }
}
