// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct DsyncTokenCreated: Codable, Sendable, Equatable {
    /// Distinguishes the Event object.
    public let object: String
    /// Unique identifier for the event.
    public let id: String
    public let event: String
    /// The event payload.
    public let data: DsyncTokenCreatedData
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    public let context: EventContext?

    public init(
        object: String,
        id: String,
        event: String,
        data: DsyncTokenCreatedData,
        createdAt: Date,
        context: EventContext? = nil
    ) {
        self.object = object
        self.id = id
        self.event = event
        self.data = data
        self.createdAt = createdAt
        self.context = context
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case event
        case data
        case createdAt = "created_at"
        case context
    }
}
