// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct EmailVerificationCodeSessionAuthenticateRequest: Codable, Sendable, Equatable {
    /// The client ID of the application.
    public let clientId: String
    /// The client secret of the application.
    public let clientSecret: String
    public let grantType: String
    /// The email verification code.
    public let code: String
    /// The pending authentication token from a previous authentication attempt.
    public let pendingAuthenticationToken: String
    /// The IP address of the user's request.
    public let ipAddress: String?
    /// A unique identifier for the device.
    public let deviceId: String?
    /// The user agent string from the user's browser.
    public let userAgent: String?

    public init(
        clientId: String,
        clientSecret: String,
        grantType: String,
        code: String,
        pendingAuthenticationToken: String,
        ipAddress: String? = nil,
        deviceId: String? = nil,
        userAgent: String? = nil
    ) {
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.grantType = grantType
        self.code = code
        self.pendingAuthenticationToken = pendingAuthenticationToken
        self.ipAddress = ipAddress
        self.deviceId = deviceId
        self.userAgent = userAgent
    }

    private enum CodingKeys: String, CodingKey {
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case grantType = "grant_type"
        case code
        case pendingAuthenticationToken = "pending_authentication_token"
        case ipAddress = "ip_address"
        case deviceId = "device_id"
        case userAgent = "user_agent"
    }
}
