// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Error response body.
public struct ErrorResponse: Codable, Sendable, Equatable {
    /// A human-readable description of the error.
    public let error: String

    public init(
        error: String
    ) {
        self.error = error
    }

    private enum CodingKeys: String, CodingKey {
        case error
    }
}
