// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The actor who performed the action.
public struct EventContextActor: Codable, Sendable, Equatable {
    /// Unique identifier of the actor.
    public let id: String
    /// The source of the actor that performed the action.
    public let source: EventContextActorSource
    /// The name of the actor.
    public let name: String?

    public init(
        id: String,
        source: EventContextActorSource,
        name: String? = nil
    ) {
        self.id = id
        self.source = source
        self.name = name
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case source
        case name
    }
}
