// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Pagination cursor for navigating to the next page of results.
public struct EventListListMetadata: Codable, Sendable, Equatable {
    /// An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    public let after: String?

    public init(
        after: String? = nil
    ) {
        self.after = after
    }

    private enum CodingKeys: String, CodingKey {
        case after
    }
}
