// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct EventList: Codable, Sendable, Equatable {
    /// Indicates this is a list response.
    public let object: String
    /// The list of records for the current page.
    public let data: [EventSchema]
    /// Pagination cursor for navigating to the next page of results.
    public let listMetadata: EventListListMetadata

    public init(
        object: String,
        data: [EventSchema],
        listMetadata: EventListListMetadata
    ) {
        self.object = object
        self.data = data
        self.listMetadata = listMetadata
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case data
        case listMetadata = "list_metadata"
    }
}
