// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ExternalAuthCompleteResponse: Codable, Sendable, Equatable {
    /// URI to redirect the user back to AuthKit to complete the OAuth flow.
    public let redirectUri: String

    public init(
        redirectUri: String
    ) {
        self.redirectUri = redirectUri
    }

    private enum CodingKeys: String, CodingKey {
        case redirectUri = "redirect_uri"
    }
}
