// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The previous context attributes of the flag rule.
public struct FlagRuleUpdatedContextPreviousAttributeContext: Codable, Sendable, Equatable {
    /// The previous access type of the flag rule.
    public let accessType: FlagRuleUpdatedContextPreviousAttributeContextAccessType?
    /// The previous configured targets for the flag rule.
    public let configuredTargets: FlagRuleUpdatedContextPreviousAttributeContextConfiguredTarget?

    public init(
        accessType: FlagRuleUpdatedContextPreviousAttributeContextAccessType? = nil,
        configuredTargets: FlagRuleUpdatedContextPreviousAttributeContextConfiguredTarget? = nil
    ) {
        self.accessType = accessType
        self.configuredTargets = configuredTargets
    }

    private enum CodingKeys: String, CodingKey {
        case accessType = "access_type"
        case configuredTargets = "configured_targets"
    }
}
