// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The previous data attributes of the flag.
public struct FlagUpdatedContextPreviousAttributeData: Codable, Sendable, Equatable {
    /// The previous name of the flag.
    public let name: String?
    /// The previous description of the flag.
    public let description: String?
    /// The previous tags of the flag.
    public let tags: [String]?
    /// Whether the flag was previously enabled.
    public let enabled: Bool?
    /// The previous default value of the flag.
    public let defaultValue: Bool?

    public init(
        name: String? = nil,
        description: String? = nil,
        tags: [String]? = nil,
        enabled: Bool? = nil,
        defaultValue: Bool? = nil
    ) {
        self.name = name
        self.description = description
        self.tags = tags
        self.enabled = enabled
        self.defaultValue = defaultValue
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case description
        case tags
        case enabled
        case defaultValue = "default_value"
    }
}
