// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct GroupMemberRemovedData: Codable, Sendable, Equatable {
    /// The ID of the Group.
    public let groupId: String
    /// The ID of the OrganizationMembership.
    public let organizationMembershipId: String

    public init(
        groupId: String,
        organizationMembershipId: String
    ) {
        self.groupId = groupId
        self.organizationMembershipId = organizationMembershipId
    }

    private enum CodingKeys: String, CodingKey {
        case groupId = "group_id"
        case organizationMembershipId = "organization_membership_id"
    }
}
