// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct InviteItContact: Codable, Sendable, Equatable {
    /// The Admin Portal features that the IT contact can configure.
    public let intents: [InviteItContactIntents]

    public init(
        intents: [InviteItContactIntents]
    ) {
        self.intents = intents
    }

    private enum CodingKeys: String, CodingKey {
        case intents
    }
}
