// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ItContact: Codable, Sendable, Equatable {
    /// The IT Contact object.
    public let object: String
    /// The unique ID of the IT Contact.
    public let id: String
    /// The email address of the IT Contact.
    public let email: String
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        email: String,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.object = object
        self.id = id
        self.email = email
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case email
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
