// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct JwksResponse: Codable, Sendable, Equatable {
    /// The public keys used for verifying access tokens.
    public let keys: [JwksResponseKeys]

    public init(
        keys: [JwksResponseKeys]
    ) {
        self.keys = keys
    }

    private enum CodingKeys: String, CodingKey {
        case keys
    }
}
