// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct MagicAuthSendMagicAuthCodeAndReturnResponse: Codable, Sendable, Equatable {
    /// Distinguishes the Magic Auth object.
    public let object: String
    /// The unique ID of the Magic Auth code.
    public let id: String
    /// The unique ID of the user.
    public let userId: String
    /// The email address of the user.
    public let email: String
    /// The timestamp when the Magic Auth code expires.
    public let expiresAt: Date
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date
    /// The code used to verify the Magic Auth code.
    public let code: String
    /// The ID of the Radar authentication attempt created for this request when Radar is enabled. Pass this value to the authenticate endpoint to associate the subsequent authentication with this Radar attempt.
    public let radarAuthAttemptId: String?

    public init(
        object: String,
        id: String,
        userId: String,
        email: String,
        expiresAt: Date,
        createdAt: Date,
        updatedAt: Date,
        code: String,
        radarAuthAttemptId: String? = nil
    ) {
        self.object = object
        self.id = id
        self.userId = userId
        self.email = email
        self.expiresAt = expiresAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.code = code
        self.radarAuthAttemptId = radarAuthAttemptId
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case userId = "user_id"
        case email
        case expiresAt = "expires_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case code
        case radarAuthAttemptId = "radar_auth_attempt_id"
    }
}
