// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct MagicAuthCreatedData: Codable, Sendable, Equatable {
    /// Distinguishes the Magic Auth object.
    public let object: String
    /// The unique ID of the Magic Auth code.
    public let id: String
    /// The unique ID of the user.
    public let userId: String
    /// The email address of the user.
    public let email: String
    /// The timestamp when the Magic Auth code expires.
    public let expiresAt: Date
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        userId: String,
        email: String,
        expiresAt: Date,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.object = object
        self.id = id
        self.userId = userId
        self.email = email
        self.expiresAt = expiresAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case userId = "user_id"
        case email
        case expiresAt = "expires_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
