// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ObjectListResponse: Codable, Sendable, Equatable {
    /// List of object summaries.
    public let data: [ObjectSummary]
    public let listMetadata: ListMetadata

    public init(
        data: [ObjectSummary],
        listMetadata: ListMetadata
    ) {
        self.data = data
        self.listMetadata = listMetadata
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case listMetadata = "list_metadata"
    }
}
