// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct OrganizationMembershipDeletedData: Codable, Sendable, Equatable {
    /// Distinguishes the organization membership object.
    public let object: String
    /// Unique identifier of the organization membership.
    public let id: String
    /// The ID of the user.
    public let userId: String
    /// The ID of the organization.
    public let organizationId: String
    /// The status of the organization membership.
    public let status: OrganizationMembershipDeletedDataStatus
    /// The role associated with the membership.
    public let role: SlimRole
    /// The roles associated with the membership.
    public let roles: [SlimRole]?
    /// Custom attributes associated with the membership.
    public let customAttributes: [String: AnyCodable]
    /// Whether the membership is managed by a directory sync provider.
    public let directoryManaged: Bool
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        userId: String,
        organizationId: String,
        status: OrganizationMembershipDeletedDataStatus,
        role: SlimRole,
        customAttributes: [String: AnyCodable],
        directoryManaged: Bool,
        createdAt: Date,
        updatedAt: Date,
        roles: [SlimRole]? = nil
    ) {
        self.object = object
        self.id = id
        self.userId = userId
        self.organizationId = organizationId
        self.status = status
        self.role = role
        self.roles = roles
        self.customAttributes = customAttributes
        self.directoryManaged = directoryManaged
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case userId = "user_id"
        case organizationId = "organization_id"
        case status
        case role
        case roles
        case customAttributes = "custom_attributes"
        case directoryManaged = "directory_managed"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
