// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The entity that owns the API Key.
public struct OrganizationApiKeyWithValueOwner: Codable, Sendable, Equatable {
    /// The type of the API Key owner.
    public let type: String
    /// Unique identifier of the API Key owner.
    public let id: String

    public init(
        type: String,
        id: String
    ) {
        self.type = type
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case type
        case id
    }
}
