// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct OrganizationDomainVerificationFailedData: Codable, Sendable, Equatable {
    /// The reason the domain verification failed.
    public let reason: OrganizationDomainVerificationFailedDataReason
    /// The organization domain that failed verification.
    public let organizationDomain: OrganizationDomainVerificationFailedDataOrganizationDomain

    public init(
        reason: OrganizationDomainVerificationFailedDataReason,
        organizationDomain: OrganizationDomainVerificationFailedDataOrganizationDomain
    ) {
        self.reason = reason
        self.organizationDomain = organizationDomain
    }

    private enum CodingKeys: String, CodingKey {
        case reason
        case organizationDomain = "organization_domain"
    }
}
