// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct PatchConnectionSAMLOptions: Codable, Sendable, Equatable {
    /// The Identity Provider metadata URL. When provided, the IdP fields and signing certificates are re-imported from the metadata document, replacing the current set. Mutually exclusive with the manual IdP fields. Set to `null` to stop tracking a metadata URL.
    public let idpMetadataUrl: String?
    /// A custom Assertion Consumer Service (ACS) URL override. Set to `null` to revert to the standard WorkOS-generated ACS URL.
    public let acsUrl: String?
    /// A custom Service Provider Entity ID (audience) override. Set to `null` to revert to the connection external key.
    public let spEntityId: String?
    /// The Identity Provider Entity ID.
    public let idpEntityId: String?
    /// The Identity Provider SSO URL.
    public let idpSSOUrl: String?

    public init(
        idpMetadataUrl: String? = nil,
        acsUrl: String? = nil,
        spEntityId: String? = nil,
        idpEntityId: String? = nil,
        idpSSOUrl: String? = nil
    ) {
        self.idpMetadataUrl = idpMetadataUrl
        self.acsUrl = acsUrl
        self.spEntityId = spEntityId
        self.idpEntityId = idpEntityId
        self.idpSSOUrl = idpSSOUrl
    }

    private enum CodingKeys: String, CodingKey {
        case idpMetadataUrl = "idp_metadata_url"
        case acsUrl = "acs_url"
        case spEntityId = "sp_entity_id"
        case idpEntityId = "idp_entity_id"
        case idpSSOUrl = "idp_sso_url"
    }
}
