// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct PipesConnectedAccountConnectionFailedData: Codable, Sendable, Equatable {
    /// The object type.
    public let object: String
    /// The unique ID of the data integration.
    public let dataIntegrationId: String
    /// The provider slug for this connection attempt.
    public let providerSlug: String
    /// The ID of the User the connection attempt belongs to.
    public let userId: String?
    /// The ID of the Organization the connection attempt belongs to.
    public let organizationId: String?
    /// A machine-readable error code for the failure.
    public let errorCode: String
    /// A human-readable explanation of the failure.
    public let errorReason: String?
    /// The raw error code returned by the OAuth provider.
    public let providerError: String?
    /// The raw error description returned by the OAuth provider.
    public let providerErrorDescription: String?
    /// An ISO 8601 timestamp.
    public let createdAt: Date

    public init(
        object: String,
        dataIntegrationId: String,
        providerSlug: String,
        errorCode: String,
        createdAt: Date,
        userId: String? = nil,
        organizationId: String? = nil,
        errorReason: String? = nil,
        providerError: String? = nil,
        providerErrorDescription: String? = nil
    ) {
        self.object = object
        self.dataIntegrationId = dataIntegrationId
        self.providerSlug = providerSlug
        self.userId = userId
        self.organizationId = organizationId
        self.errorCode = errorCode
        self.errorReason = errorReason
        self.providerError = providerError
        self.providerErrorDescription = providerErrorDescription
        self.createdAt = createdAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case dataIntegrationId = "data_integration_id"
        case providerSlug = "provider_slug"
        case userId = "user_id"
        case organizationId = "organization_id"
        case errorCode = "error_code"
        case errorReason = "error_reason"
        case providerError = "provider_error"
        case providerErrorDescription = "provider_error_description"
        case createdAt = "created_at"
    }
}
