// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct RadarChallenge: Codable, Sendable, Equatable {
    /// Distinguishes the Radar Challenge object.
    public let object: String
    /// The unique ID of the Radar Challenge.
    public let id: String
    /// The type of the Radar challenge.
    public let type: String
    /// The unique ID of the user.
    public let userId: String
    /// The email address of the user.
    public let email: String
    /// The timestamp when the Radar Challenge code expires.
    public let expiresAt: Date
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date
    /// The code used to verify the Radar Challenge.
    public let code: String

    public init(
        object: String,
        id: String,
        type: String,
        userId: String,
        email: String,
        expiresAt: Date,
        createdAt: Date,
        updatedAt: Date,
        code: String
    ) {
        self.object = object
        self.id = id
        self.type = type
        self.userId = userId
        self.email = email
        self.expiresAt = expiresAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.code = code
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case type
        case userId = "user_id"
        case email
        case expiresAt = "expires_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case code
    }
}
