// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct RadarListEntryAlreadyPresentResponse: Codable, Sendable, Equatable {
    /// A message indicating the entry already exists.
    public let message: String

    public init(
        message: String
    ) {
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case message
    }
}
