// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ReauthorizeDataIntegrationsUpsertApiKeyRequest: Codable, Sendable, Equatable {
    /// A [User](https://workos.com/docs/reference/authkit/user) identifier.
    public let userId: String
    /// An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. Required when `connection_owner` is `organization`.
    public let organizationId: String?
    /// Whose connection to create or rotate. `user` (the default) addresses the connection owned by `user_id`. `organization` addresses the connection shared by every member of `organization_id`; `user_id` then identifies the member performing the request and must be an active member of the organization.
    public let connectionOwner: ReauthorizeDataIntegrationsUpsertApiKeyRequestConnectionOwner?
    /// The API key secret to store for this integration.
    public let secret: String
    /// Reauthorize exactly the connection named by `connected_account_id`.
    public let connectionIntent: String
    /// The exact connected account to reauthorize. Required with `connection_intent: reauthorize`.
    public let connectedAccountId: String

    public init(
        userId: String,
        secret: String,
        connectionIntent: String,
        connectedAccountId: String,
        organizationId: String? = nil,
        connectionOwner: ReauthorizeDataIntegrationsUpsertApiKeyRequestConnectionOwner? = nil
    ) {
        self.userId = userId
        self.organizationId = organizationId
        self.connectionOwner = connectionOwner
        self.secret = secret
        self.connectionIntent = connectionIntent
        self.connectedAccountId = connectedAccountId
    }

    private enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case organizationId = "organization_id"
        case connectionOwner = "connection_owner"
        case secret
        case connectionIntent = "connection_intent"
        case connectedAccountId = "connected_account_id"
    }
}
