// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct RefreshTokenSessionAuthenticateRequest: Codable, Sendable, Equatable {
    /// The client ID of the application.
    public let clientId: String
    /// The client secret of the application. May be omitted by public clients that authenticate through other means, such as a PKCE `code_verifier`.
    public let clientSecret: String?
    public let grantType: String
    /// The refresh token to exchange for new tokens.
    public let refreshToken: String
    /// The ID of the organization to scope the session to.
    public let organizationId: String?
    /// The IP address of the user's request.
    public let ipAddress: String?
    /// A unique identifier for the device.
    public let deviceId: String?
    /// The user agent string from the user's browser.
    public let userAgent: String?

    public init(
        clientId: String,
        grantType: String,
        refreshToken: String,
        clientSecret: String? = nil,
        organizationId: String? = nil,
        ipAddress: String? = nil,
        deviceId: String? = nil,
        userAgent: String? = nil
    ) {
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.grantType = grantType
        self.refreshToken = refreshToken
        self.organizationId = organizationId
        self.ipAddress = ipAddress
        self.deviceId = deviceId
        self.userAgent = userAgent
    }

    private enum CodingKeys: String, CodingKey {
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case grantType = "grant_type"
        case refreshToken = "refresh_token"
        case organizationId = "organization_id"
        case ipAddress = "ip_address"
        case deviceId = "device_id"
        case userAgent = "user_agent"
    }
}
