// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct ResendUserInviteOptions: Codable, Sendable, Equatable {
    /// The locale to use when rendering the invitation email. See [supported locales](https://workos.com/docs/authkit/hosted-ui/localization).
    public let locale: ResendUserInviteOptionsLocale?

    public init(
        locale: ResendUserInviteOptionsLocale? = nil
    ) {
        self.locale = locale
    }

    private enum CodingKeys: String, CodingKey {
        case locale
    }
}
