// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct ResourceExportCreatedData: Codable, Sendable, Equatable {
    /// The ID of the resource export.
    public let id: String
    /// The type of resource being exported.
    public let resourceType: ResourceExportCreatedDataResourceType

    public init(
        id: String,
        resourceType: ResourceExportCreatedDataResourceType
    ) {
        self.id = id
        self.resourceType = resourceType
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case resourceType = "resource_type"
    }
}
