// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct SAMLIdpSigningCertificateList: Codable, Sendable, Equatable {
    public let object: String
    /// Every Identity Provider signing certificate on the Connection, including expired ones, oldest first.
    public let data: [SAMLIdpSigningCertificate]

    public init(
        object: String,
        data: [SAMLIdpSigningCertificate]
    ) {
        self.object = object
        self.data = data
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case data
    }
}
