// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct SAMLSpSigningCertificate: Codable, Sendable, Equatable {
    /// Distinguishes the SAML Service Provider signing certificate object.
    public let object: String
    /// Unique identifier for the Service Provider signing key pair. WorkOS holds the corresponding private key, which is never exposed.
    public let id: String
    /// The PEM-encoded public X.509 certificate.
    public let value: String
    /// When the certificate becomes valid.
    public let notBefore: Date?
    /// When the certificate expires.
    public let notAfter: Date?
    /// An ISO 8601 timestamp.
    public let createdAt: Date

    public init(
        object: String,
        id: String,
        value: String,
        createdAt: Date,
        notBefore: Date? = nil,
        notAfter: Date? = nil
    ) {
        self.object = object
        self.id = id
        self.value = value
        self.notBefore = notBefore
        self.notAfter = notAfter
        self.createdAt = createdAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case value
        case notBefore = "not_before"
        case notAfter = "not_after"
        case createdAt = "created_at"
    }
}
