// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct SendVerificationEmailResponse: Codable, Sendable, Equatable {
    /// The user to whom the verification email was sent.
    public let user: User

    public init(
        user: User
    ) {
        self.user = user
    }

    private enum CodingKeys: String, CodingKey {
        case user
    }
}
