// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct SendRadarSmsChallenge: Codable, Sendable, Equatable {
    /// The ID of the user to send the SMS challenge to.
    public let userId: String
    /// The pending authentication token from a previous authentication attempt that triggered the Radar challenge.
    public let pendingAuthenticationToken: String
    /// The phone number to send the SMS verification code to.
    public let phoneNumber: String
    /// The IP address of the user's request.
    public let ipAddress: String?
    /// The user agent string from the user's request.
    public let userAgent: String?

    public init(
        userId: String,
        pendingAuthenticationToken: String,
        phoneNumber: String,
        ipAddress: String? = nil,
        userAgent: String? = nil
    ) {
        self.userId = userId
        self.pendingAuthenticationToken = pendingAuthenticationToken
        self.phoneNumber = phoneNumber
        self.ipAddress = ipAddress
        self.userAgent = userAgent
    }

    private enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case pendingAuthenticationToken = "pending_authentication_token"
        case phoneNumber = "phone_number"
        case ipAddress = "ip_address"
        case userAgent = "user_agent"
    }
}
