// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct SSODeviceAuthorizationRequest: Codable, Sendable, Equatable {
    /// The WorkOS client ID for your application.
    public let clientId: String

    public init(
        clientId: String
    ) {
        self.clientId = clientId
    }

    private enum CodingKeys: String, CodingKey {
        case clientId = "client_id"
    }
}
