// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct SSOLogoutAuthorizeResponse: Codable, Sendable, Equatable {
    /// The URL to redirect the user to in order to log out ([Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint ready to use).
    public let logoutUrl: String
    /// The logout token to be used in the [Logout Redirect](https://workos.com/docs/reference/sso/logout) endpoint.
    public let logoutToken: String

    public init(
        logoutUrl: String,
        logoutToken: String
    ) {
        self.logoutUrl = logoutUrl
        self.logoutToken = logoutToken
    }

    private enum CodingKeys: String, CodingKey {
        case logoutUrl = "logout_url"
        case logoutToken = "logout_token"
    }
}
