// This file is auto-generated by oagen. Do not edit.

import Foundation

/// OAuth tokens issued by the identity provider, if available.
public struct SSOTokenResponseOAuthToken: Codable, Sendable, Equatable {
    /// The OAuth provider used for authentication.
    public let provider: String
    /// The refresh token from the OAuth provider.
    public let refreshToken: String
    /// The access token from the OAuth provider.
    public let accessToken: String
    /// The timestamp at which the access token expires.
    public let expiresAt: Int
    /// A list of OAuth scopes for which the access token is authorized.
    public let scopes: [String]

    public init(
        provider: String,
        refreshToken: String,
        accessToken: String,
        expiresAt: Int,
        scopes: [String]
    ) {
        self.provider = provider
        self.refreshToken = refreshToken
        self.accessToken = accessToken
        self.expiresAt = expiresAt
        self.scopes = scopes
    }

    private enum CodingKeys: String, CodingKey {
        case provider
        case refreshToken = "refresh_token"
        case accessToken = "access_token"
        case expiresAt = "expires_at"
        case scopes
    }
}
