// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UpdateObjectRequest: Codable, Sendable, Equatable {
    /// New plaintext value.
    public let value: String
    /// ID of the expected current version for optimistic locking.
    public let versionCheck: String?

    public init(
        value: String,
        versionCheck: String? = nil
    ) {
        self.value = value
        self.versionCheck = versionCheck
    }

    private enum CodingKeys: String, CodingKey {
        case value
        case versionCheck = "version_check"
    }
}
