// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UpdateAuditLogsRetention: Codable, Sendable, Equatable {
    /// The number of days Audit Log events will be retained. Valid values are `30` and `365`.
    public let retentionPeriodInDays: Int

    public init(
        retentionPeriodInDays: Int
    ) {
        self.retentionPeriodInDays = retentionPeriodInDays
    }

    private enum CodingKeys: String, CodingKey {
        case retentionPeriodInDays = "retention_period_in_days"
    }
}
