// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UpdateJWTTemplate: Codable, Sendable, Equatable {
    /// The JWT template content as a Liquid template string.
    public let content: String

    public init(
        content: String
    ) {
        self.content = content
    }

    private enum CodingKeys: String, CodingKey {
        case content
    }
}
