// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UpdateGroup: Codable, Sendable, Equatable {
    /// The name of the Group.
    public let name: String?
    /// An optional description of the Group.
    public let description: String?

    public init(
        name: String? = nil,
        description: String? = nil
    ) {
        self.name = name
        self.description = description
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case description
    }
}
