// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UpdateUser: Codable, Sendable, Equatable {
    /// The email address of the user.
    public let email: String?
    /// The first name of the user.
    public let firstName: String?
    /// The last name of the user.
    public let lastName: String?
    /// The user's full name.
    public let name: String?
    /// Whether the user's email has been verified.
    public let emailVerified: Bool?
    /// Object containing metadata key/value pairs associated with the user.
    public let metadata: [String: String]?
    /// The external ID of the user.
    public let externalId: String?
    /// The user's preferred locale.
    public let locale: String?
    /// The password to set for the user. Mutually exclusive with `password_hash` and `password_hash_type`.
    public let password: String?
    /// The hashed password to set for the user. Required with `password_hash_type`. Mutually exclusive with `password`.
    public let passwordHash: String?
    /// The algorithm originally used to hash the password, used when providing a `password_hash`. Required with `password_hash`. Mutually exclusive with `password`.
    public let passwordHashType: UpdateUserPasswordHashType?

    public init(
        email: String? = nil,
        firstName: String? = nil,
        lastName: String? = nil,
        name: String? = nil,
        emailVerified: Bool? = nil,
        metadata: [String: String]? = nil,
        externalId: String? = nil,
        locale: String? = nil,
        password: String? = nil,
        passwordHash: String? = nil,
        passwordHashType: UpdateUserPasswordHashType? = nil
    ) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.name = name
        self.emailVerified = emailVerified
        self.metadata = metadata
        self.externalId = externalId
        self.locale = locale
        self.password = password
        self.passwordHash = passwordHash
        self.passwordHashType = passwordHashType
    }

    private enum CodingKeys: String, CodingKey {
        case email
        case firstName = "first_name"
        case lastName = "last_name"
        case name
        case emailVerified = "email_verified"
        case metadata
        case externalId = "external_id"
        case locale
        case password
        case passwordHash = "password_hash"
        case passwordHashType = "password_hash_type"
    }
}
