// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UpdateAuditLogsRetention: Codable, Sendable, Equatable {
    /// The period Audit Log events will be retained. Valid values are `1_MONTH` through `11_MONTHS` in one-month increments and `1_YEAR` through `10_YEARS` in one-year increments. Mutually exclusive with `retention_period_in_days`.
    public let retentionPeriod: UpdateAuditLogsRetentionRetentionPeriod?
    /// The number of days Audit Log events will be retained. Valid values are `30` through `330` in 30-day increments and `365` through `3650` in 365-day increments. Deprecated: use `retention_period` instead. Mutually exclusive with `retention_period`.
    @available(*, deprecated)
    public let retentionPeriodInDays: Int?

    public init(
        retentionPeriod: UpdateAuditLogsRetentionRetentionPeriod? = nil,
        retentionPeriodInDays: Int? = nil
    ) {
        self.retentionPeriod = retentionPeriod
        self.retentionPeriodInDays = retentionPeriodInDays
    }

    private enum CodingKeys: String, CodingKey {
        case retentionPeriod = "retention_period"
        case retentionPeriodInDays = "retention_period_in_days"
    }
}
