// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UserRoleAssignment: Codable, Sendable, Equatable {
    /// Distinguishes the role assignment object.
    public let object: String
    /// Unique identifier of the role assignment.
    public let id: String
    /// The ID of the organization membership the role is assigned to.
    public let organizationMembershipId: String
    /// The role included in the assignment.
    public let role: SlimRole
    /// The resource the role is assigned on.
    public let resource: UserRoleAssignmentResource
    /// The origin of the role assignment.
    public let source: UserRoleAssignmentSource
    /// An ISO 8601 timestamp.
    public let createdAt: Date
    /// An ISO 8601 timestamp.
    public let updatedAt: Date

    public init(
        object: String,
        id: String,
        organizationMembershipId: String,
        role: SlimRole,
        resource: UserRoleAssignmentResource,
        source: UserRoleAssignmentSource,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.object = object
        self.id = id
        self.organizationMembershipId = organizationMembershipId
        self.role = role
        self.resource = resource
        self.source = source
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case id
        case organizationMembershipId = "organization_membership_id"
        case role
        case resource
        case source
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
