// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UserInviteList: Codable, Sendable, Equatable {
    /// Indicates this is a list response.
    public let object: String
    /// The list of records for the current page.
    public let data: [UserInvite]
    /// Pagination cursors for navigating between pages of results.
    public let listMetadata: UserInviteListListMetadata

    public init(
        object: String,
        data: [UserInvite],
        listMetadata: UserInviteListListMetadata
    ) {
        self.object = object
        self.data = data
        self.listMetadata = listMetadata
    }

    private enum CodingKeys: String, CodingKey {
        case object
        case data
        case listMetadata = "list_metadata"
    }
}
