// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UserIdentitiesGetItem: Codable, Sendable, Equatable {
    /// The unique ID of the user in the external identity provider.
    public let idpId: String
    /// The type of the identity.
    public let type: String
    /// The type of OAuth provider for the identity.
    public let provider: UserIdentitiesGetItemProvider

    public init(
        idpId: String,
        type: String,
        provider: UserIdentitiesGetItemProvider
    ) {
        self.idpId = idpId
        self.type = type
        self.provider = provider
    }

    private enum CodingKeys: String, CodingKey {
        case idpId = "idp_id"
        case type
        case provider
    }
}
