// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The origin of the role assignment.
public struct UserRoleAssignmentSource: Codable, Sendable, Equatable {
    /// Whether the role was assigned directly or derived from a group.
    public let type: UserRoleAssignmentSourceType
    /// The ID of the group role assignment the role was derived from, or null if direct.
    public let groupRoleAssignmentId: String?

    public init(
        type: UserRoleAssignmentSourceType,
        groupRoleAssignmentId: String? = nil
    ) {
        self.type = type
        self.groupRoleAssignmentId = groupRoleAssignmentId
    }

    private enum CodingKeys: String, CodingKey {
        case type
        case groupRoleAssignmentId = "group_role_assignment_id"
    }
}
