// This file is auto-generated by oagen. Do not edit.

import Foundation

public struct UserObject: Codable, Sendable, Equatable {
    /// Your application's user identifier, which will be stored as an [`external_id`](https://workos.com/docs/authkit/metadata/external-identifiers). Used for upserting and deduplication.
    public let id: String
    /// The user's email address.
    public let email: String
    /// The user's first name.
    public let firstName: String?
    /// The user's last name.
    public let lastName: String?
    /// The user's full name.
    public let name: String?
    /// A set of key-value pairs to attach to the user.
    public let metadata: [String: String]?

    public init(
        id: String,
        email: String,
        firstName: String? = nil,
        lastName: String? = nil,
        name: String? = nil,
        metadata: [String: String]? = nil
    ) {
        self.id = id
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.name = name
        self.metadata = metadata
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case email
        case firstName = "first_name"
        case lastName = "last_name"
        case name
        case metadata
    }
}
