// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct VaultDataUpdatedData: Codable, Sendable, Equatable {
    /// The unique identifier of the actor.
    public let actorId: String
    public let actorSource: VaultDataUpdatedDataActorSource
    /// The name of the actor.
    public let actorName: String
    /// The name of the key-value store.
    public let kvName: String
    /// The unique identifier of the encryption key.
    public let keyId: String
    public let keyContext: [String: String]

    public init(
        actorId: String,
        actorSource: VaultDataUpdatedDataActorSource,
        actorName: String,
        kvName: String,
        keyId: String,
        keyContext: [String: String]
    ) {
        self.actorId = actorId
        self.actorSource = actorSource
        self.actorName = actorName
        self.kvName = kvName
        self.keyId = keyId
        self.keyContext = keyContext
    }

    private enum CodingKeys: String, CodingKey {
        case actorId = "actor_id"
        case actorSource = "actor_source"
        case actorName = "actor_name"
        case kvName = "kv_name"
        case keyId = "key_id"
        case keyContext = "key_context"
    }
}
