// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct VaultDekReadData: Codable, Sendable, Equatable {
    /// The unique identifier of the actor.
    public let actorId: String
    public let actorSource: VaultDekReadDataActorSource
    /// The name of the actor.
    public let actorName: String
    /// The unique identifiers of the data encryption keys.
    public let keyIds: [String]
    public let keyContext: [String: String]

    public init(
        actorId: String,
        actorSource: VaultDekReadDataActorSource,
        actorName: String,
        keyIds: [String],
        keyContext: [String: String]
    ) {
        self.actorId = actorId
        self.actorSource = actorSource
        self.actorName = actorName
        self.keyIds = keyIds
        self.keyContext = keyContext
    }

    private enum CodingKeys: String, CodingKey {
        case actorId = "actor_id"
        case actorSource = "actor_source"
        case actorName = "actor_name"
        case keyIds = "key_ids"
        case keyContext = "key_context"
    }
}
