// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct VaultKekCreatedData: Codable, Sendable, Equatable {
    /// The unique identifier of the actor.
    public let actorId: String
    public let actorSource: VaultKekCreatedDataActorSource
    /// The name of the actor.
    public let actorName: String
    /// The name of the key encryption key.
    public let keyName: String
    /// The unique identifier of the key encryption key.
    public let keyId: String

    public init(
        actorId: String,
        actorSource: VaultKekCreatedDataActorSource,
        actorName: String,
        keyName: String,
        keyId: String
    ) {
        self.actorId = actorId
        self.actorSource = actorSource
        self.actorName = actorName
        self.keyName = keyName
        self.keyId = keyId
    }

    private enum CodingKeys: String, CodingKey {
        case actorId = "actor_id"
        case actorSource = "actor_source"
        case actorName = "actor_name"
        case keyName = "key_name"
        case keyId = "key_id"
    }
}
