// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The event payload.
public struct VaultByokKeyVerificationCompletedData: Codable, Sendable, Equatable {
    /// The unique identifier of the organization.
    public let organizationId: String
    public let keyProvider: VaultByokKeyProvider
    /// Whether the BYOK key verification completed successfully.
    public let verified: Bool

    public init(
        organizationId: String,
        keyProvider: VaultByokKeyProvider,
        verified: Bool
    ) {
        self.organizationId = organizationId
        self.keyProvider = keyProvider
        self.verified = verified
    }

    private enum CodingKeys: String, CodingKey {
        case organizationId = "organization_id"
        case keyProvider = "key_provider"
        case verified
    }
}
