// This file is auto-generated by oagen. Do not edit.

import Foundation
import Testing

@testable import WorkOS

@Suite struct ApiKeysTests {
    @Test func resourceIsReachable() {
        let client = makeTestClient()
        _ = client.apiKeys
        #expect(client.configuration.apiKey == "sk_test_123")
    }
}
