// This file is auto-generated by oagen. Do not edit.

import Testing
import Foundation
@testable import workos

@Suite struct MultiFactorAuthTests {
    @Test func resourceIsReachable() {
        let client = makeTestClient()
        _ = client.multiFactorAuth
        #expect(client.configuration.apiKey == "sk_test_123")
    }
}
