// This file is auto-generated by oagen. Do not edit.

import Foundation
import Testing

@testable import WorkOS

private struct EmptyBody: Codable {}

/// Behavioral tests for the shared transport: authentication, per-request
/// options, typed error mapping, retries, and idempotency.
@Suite struct TransportBehaviorTests {
    @Test func sendsAuthorizationAndUserAgentHeaders() async throws {
        let (client, recorder) = makeTestClient()
        _ = try await client.transport.request(
            method: "GET", path: "things", query: [], body: nil, options: nil, as: EmptyBody.self)

        let request = try #require(recorder.lastRequest)
        #expect(request.value(forHTTPHeaderField: "Authorization") == "Bearer sk_test_123")
        #expect(request.value(forHTTPHeaderField: "User-Agent")?.isEmpty == false)
    }

    @Test func requestOptionsOverrideHeadersAndTimeout() async throws {
        let (client, recorder) = makeTestClient()
        let options = RequestOptions(additionalHeaders: ["X-Test-Header": "test-value"], timeout: 5)
        _ = try await client.transport.request(
            method: "GET", path: "things", query: [], body: nil, options: options,
            as: EmptyBody.self)

        let request = try #require(recorder.lastRequest)
        #expect(request.value(forHTTPHeaderField: "X-Test-Header") == "test-value")
        #expect(request.timeoutInterval == 5)
    }

    @Test func mapsErrorStatusToTypedError() async throws {
        let errorBody = #"{"message":"Not found","code":"entity_not_found","request_id":"req_123"}"#
        let (client, _) = makeTestClient(statusCode: 404, responding: errorBody)
        do {
            _ = try await client.transport.request(
                method: "GET", path: "things/thing_123", query: [], body: nil, options: nil,
                as: EmptyBody.self)
            Issue.record("expected a typed error to be thrown")
        } catch let error as WorkOSError {
            guard case .notFound(let apiError) = error else {
                Issue.record("expected WorkOSError.notFound, got \(error)")
                return
            }
            #expect(apiError.statusCode == 404)
            #expect(apiError.message == "Not found")
            #expect(apiError.code == "entity_not_found")
            #expect(apiError.requestID == "req_123")
        }
    }

    @Test func retriesRetryableStatusThenSucceeds() async throws {
        let (client, recorder) = makeTestClient(stubs: [
            .init(statusCode: 429, data: Data("{}".utf8), headers: ["Retry-After": "0"]),
            .init(statusCode: 200, data: Data("{}".utf8), headers: [:]),
        ])
        _ = try await client.transport.request(
            method: "GET", path: "things", query: [], body: nil, options: nil, as: EmptyBody.self)

        #expect(recorder.allRequests.count == 2)
    }

    @Test func postRequestsCarryAnIdempotencyKey() async throws {
        let (client, recorder) = makeTestClient()
        _ = try await client.transport.request(
            method: "POST", path: "things", query: [], body: nil, options: nil, as: EmptyBody.self)

        let request = try #require(recorder.lastRequest)
        #expect(request.value(forHTTPHeaderField: "Idempotency-Key")?.isEmpty == false)
    }

    @Test func explicitIdempotencyKeyIsHonored() async throws {
        let (client, recorder) = makeTestClient()
        let options = RequestOptions(idempotencyKey: "key_123")
        _ = try await client.transport.request(
            method: "POST", path: "things", query: [], body: nil, options: options,
            as: EmptyBody.self)

        let request = try #require(recorder.lastRequest)
        #expect(request.value(forHTTPHeaderField: "Idempotency-Key") == "key_123")
    }
}
