// This file is auto-generated by oagen. Do not edit.

import Foundation

#if canImport(FoundationNetworking)
    import FoundationNetworking
#endif

/// A URLProtocol that serves queued canned responses and records outgoing
/// requests, keyed by request host. Every test client uses a unique mock host,
/// so parallel Swift Testing execution never observes another test's traffic.
final class MockURLProtocol: URLProtocol {
    struct Stub {
        let statusCode: Int
        let data: Data
        let headers: [String: String]
    }

    private static let lock = NSLock()
    private static var stubQueues: [String: [Stub]] = [:]
    private static var recordedRequests: [String: [URLRequest]] = [:]
    private static var recordedBodies: [String: [Data]] = [:]

    /// Register a queue of responses for a mock host. Each request pops the
    /// next stub; the final stub is reused once the queue is exhausted.
    static func register(host: String, stubs: [Stub]) {
        lock.lock()
        defer { lock.unlock() }
        stubQueues[host] = stubs
        recordedRequests[host] = []
        recordedBodies[host] = []
    }

    static func requests(forHost host: String) -> [URLRequest] {
        lock.lock()
        defer { lock.unlock() }
        return recordedRequests[host] ?? []
    }

    static func bodies(forHost host: String) -> [Data] {
        lock.lock()
        defer { lock.unlock() }
        return recordedBodies[host] ?? []
    }

    override class func canInit(with request: URLRequest) -> Bool { true }
    override class func canonicalRequest(for request: URLRequest) -> URLRequest { request }

    override func startLoading() {
        let host = request.url?.host ?? ""
        let stub = MockURLProtocol.consume(host: host, request: request)
        let response = HTTPURLResponse(
            url: request.url ?? URL(string: "https://example.test")!,
            statusCode: stub.statusCode,
            httpVersion: nil,
            headerFields: stub.headers
        )!
        client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
        client?.urlProtocol(self, didLoad: stub.data)
        client?.urlProtocolDidFinishLoading(self)
    }

    override func stopLoading() {}

    private static func consume(host: String, request: URLRequest) -> Stub {
        lock.lock()
        defer { lock.unlock() }
        recordedRequests[host, default: []].append(request)
        if let body = request.httpBody {
            recordedBodies[host, default: []].append(body)
        } else if let stream = request.httpBodyStream {
            recordedBodies[host, default: []].append(readStream(stream))
        }
        var queue = stubQueues[host] ?? []
        let stub =
            queue.isEmpty
            ? Stub(statusCode: 200, data: Data("{}".utf8), headers: [:]) : queue.removeFirst()
        if queue.isEmpty {
            stubQueues[host] = [stub]
        } else {
            stubQueues[host] = queue
        }
        return stub
    }

    private static func readStream(_ stream: InputStream) -> Data {
        stream.open()
        defer { stream.close() }
        var data = Data()
        let bufferSize = 4096
        let buffer = UnsafeMutablePointer<UInt8>.allocate(capacity: bufferSize)
        defer { buffer.deallocate() }
        while stream.hasBytesAvailable {
            let read = stream.read(buffer, maxLength: bufferSize)
            if read <= 0 { break }
            data.append(buffer, count: read)
        }
        return data
    }
}
