// This file is auto-generated by oagen. Do not edit.

import Foundation
@testable import workos

/// Build a client whose URLSession is backed by MockURLProtocol.
func makeTestClient(
    statusCode: Int = 200,
    responding body: String = "{}",
    headers: [String: String] = [:]
) -> workosClient {
    let sessionConfig = URLSessionConfiguration.ephemeral
    sessionConfig.protocolClasses = [MockURLProtocol.self]
    let session = URLSession(configuration: sessionConfig)
    MockURLProtocol.setStub(MockURLProtocol.Stub(statusCode: statusCode, data: Data(body.utf8), headers: headers))
    let configuration = Configuration(apiKey: "sk_test_123", baseURL: URL(string: "https://api.example.test")!)
    return workosClient(configuration: configuration, transport: Transport(configuration: configuration, session: session))
}
