// This file is auto-generated by oagen. Do not edit.

import Foundation

@testable import WorkOS

/// Reads back the requests a mocked client sent.
struct RequestRecorder {
    let host: String

    var allRequests: [URLRequest] { MockURLProtocol.requests(forHost: host) }
    var lastRequest: URLRequest? { allRequests.last }
    var lastBody: Data? { MockURLProtocol.bodies(forHost: host).last }
}

/// Build a client whose URLSession is backed by MockURLProtocol, serving the
/// given response queue from a unique per-client mock host.
func makeTestClient(stubs: [MockURLProtocol.Stub]) -> (WorkOSClient, RequestRecorder) {
    let host = "mock-\(UUID().uuidString.lowercased()).example.test"
    MockURLProtocol.register(host: host, stubs: stubs)
    let sessionConfig = URLSessionConfiguration.ephemeral
    sessionConfig.protocolClasses = [MockURLProtocol.self]
    let session = URLSession(configuration: sessionConfig)
    let configuration = Configuration(
        apiKey: "sk_test_123", baseURL: URL(string: "https://\(host)")!)
    let client = WorkOSClient(
        configuration: configuration,
        transport: Transport(configuration: configuration, session: session))
    return (client, RequestRecorder(host: host))
}

/// Convenience: a single canned response.
func makeTestClient(
    statusCode: Int = 200,
    responding body: String = "{}",
    headers: [String: String] = [:]
) -> (WorkOSClient, RequestRecorder) {
    makeTestClient(stubs: [
        MockURLProtocol.Stub(statusCode: statusCode, data: Data(body.utf8), headers: headers)
    ])
}
