// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid AgentRegistrationCreatedDataMethod values.
public enum AgentRegistrationCreatedDataMethod: RawRepresentable, Codable, Sendable, Hashable {
    case anonymous
    case serviceAuth
    case idJag
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "anonymous": self = .anonymous
        case "service_auth": self = .serviceAuth
        case "id_jag": self = .idJag
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .anonymous: return "anonymous"
        case .serviceAuth: return "service_auth"
        case .idJag: return "id_jag"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [AgentRegistrationCreatedDataMethod] = [
        .anonymous,
        .serviceAuth,
        .idJag,
    ]
}
