// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid AgentBlueprintsTokenMintTokenRequestType values.
public enum AgentBlueprintsTokenMintTokenRequestType: RawRepresentable, Codable, Sendable, Hashable
{
    case userDelegated
    case autonomous
    case agentDelegated
    case refresh
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "user_delegated": self = .userDelegated
        case "autonomous": self = .autonomous
        case "agent_delegated": self = .agentDelegated
        case "refresh": self = .refresh
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .userDelegated: return "user_delegated"
        case .autonomous: return "autonomous"
        case .agentDelegated: return "agent_delegated"
        case .refresh: return "refresh"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [AgentBlueprintsTokenMintTokenRequestType] = [
        .userDelegated,
        .autonomous,
        .agentDelegated,
        .refresh,
    ]
}
