// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid AuditLogConfigurationLogStreamType values.
public enum AuditLogConfigurationLogStreamType: RawRepresentable, Codable, Sendable, Hashable {
    case azureSentinel
    case datadog
    case genericHttps
    case googleCloudStorage
    case s3
    case snowflake
    case splunk
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "AzureSentinel": self = .azureSentinel
        case "Datadog": self = .datadog
        case "GenericHttps": self = .genericHttps
        case "GoogleCloudStorage": self = .googleCloudStorage
        case "S3": self = .s3
        case "Snowflake": self = .snowflake
        case "Splunk": self = .splunk
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .azureSentinel: return "AzureSentinel"
        case .datadog: return "Datadog"
        case .genericHttps: return "GenericHttps"
        case .googleCloudStorage: return "GoogleCloudStorage"
        case .s3: return "S3"
        case .snowflake: return "Snowflake"
        case .splunk: return "Splunk"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [AuditLogConfigurationLogStreamType] = [.azureSentinel, .datadog, .genericHttps, .googleCloudStorage, .s3, .snowflake, .splunk]
}
