// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid AuthenticationFactorsCreateRequestType values.
public enum AuthenticationFactorsCreateRequestType: RawRepresentable, Codable, Sendable, Hashable {
    case genericOtp
    case sms
    case totp
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "generic_otp": self = .genericOtp
        case "sms": self = .sms
        case "totp": self = .totp
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .genericOtp: return "generic_otp"
        case .sms: return "sms"
        case .totp: return "totp"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [AuthenticationFactorsCreateRequestType] = [
        .genericOtp,
        .sms,
        .totp,
    ]
}
