// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid AuthorizationAssignment values.
public enum AuthorizationAssignment: RawRepresentable, Codable, Sendable, Hashable {
    case direct
    case indirect
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "direct": self = .direct
        case "indirect": self = .indirect
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .direct: return "direct"
        case .indirect: return "indirect"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [AuthorizationAssignment] = [.direct, .indirect]
}
