// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid ConnectionState values.
public enum ConnectionState: RawRepresentable, Codable, Sendable, Hashable {
    case requiresType
    case draft
    case active
    case validating
    case inactive
    case deleting
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "requires_type": self = .requiresType
        case "draft": self = .draft
        case "active": self = .active
        case "validating": self = .validating
        case "inactive": self = .inactive
        case "deleting": self = .deleting
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .requiresType: return "requires_type"
        case .draft: return "draft"
        case .active: return "active"
        case .validating: return "validating"
        case .inactive: return "inactive"
        case .deleting: return "deleting"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [ConnectionState] = [.requiresType, .draft, .active, .validating, .inactive, .deleting]
}
