// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid DataIntegrationCredentialsInputType values.
public enum DataIntegrationCredentialsInputType: RawRepresentable, Codable, Sendable, Hashable {
    case custom
    case organization
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "custom": self = .custom
        case "organization": self = .organization
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .custom: return "custom"
        case .organization: return "organization"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [DataIntegrationCredentialsInputType] = [
        .custom,
        .organization,
    ]
}
