// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid DataIntegrationsListResponseDataConnectedAccountState values.
public enum DataIntegrationsListResponseDataConnectedAccountState: RawRepresentable, Codable,
    Sendable, Hashable
{
    case connected
    case needsReauthorization
    case disconnected
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "connected": self = .connected
        case "needs_reauthorization": self = .needsReauthorization
        case "disconnected": self = .disconnected
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .connected: return "connected"
        case .needsReauthorization: return "needs_reauthorization"
        case .disconnected: return "disconnected"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [DataIntegrationsListResponseDataConnectedAccountState] = [
        .connected,
        .needsReauthorization,
        .disconnected,
    ]
}
