// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid DirectoryType values.
public enum DirectoryType: RawRepresentable, Codable, Sendable, Hashable {
    case azureSCIMV20
    case bamboohr
    case breatheHr
    case cezanneHr
    case cyberarkSCIMV20
    case fourthHr
    case genericSCIMV20
    case gsuiteDirectory
    case hibob
    case sailpointSCIMV20
    case jumpCloudSCIMV20
    case oktaSCIMV20
    case oneloginSCIMV20
    case peopleHr
    case personio
    case pingfederateSCIMV20
    case ripplingSCIMV20
    case s3
    case sftp
    case sftpWorkday
    case workday
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "azure scim v2.0": self = .azureSCIMV20
        case "bamboohr": self = .bamboohr
        case "breathe hr": self = .breatheHr
        case "cezanne hr": self = .cezanneHr
        case "cyberark scim v2.0": self = .cyberarkSCIMV20
        case "fourth hr": self = .fourthHr
        case "generic scim v2.0": self = .genericSCIMV20
        case "gsuite directory": self = .gsuiteDirectory
        case "hibob": self = .hibob
        case "sailpoint scim v2.0": self = .sailpointSCIMV20
        case "jump cloud scim v2.0": self = .jumpCloudSCIMV20
        case "okta scim v2.0": self = .oktaSCIMV20
        case "onelogin scim v2.0": self = .oneloginSCIMV20
        case "people hr": self = .peopleHr
        case "personio": self = .personio
        case "pingfederate scim v2.0": self = .pingfederateSCIMV20
        case "rippling scim v2.0": self = .ripplingSCIMV20
        case "s3": self = .s3
        case "sftp": self = .sftp
        case "sftp workday": self = .sftpWorkday
        case "workday": self = .workday
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .azureSCIMV20: return "azure scim v2.0"
        case .bamboohr: return "bamboohr"
        case .breatheHr: return "breathe hr"
        case .cezanneHr: return "cezanne hr"
        case .cyberarkSCIMV20: return "cyberark scim v2.0"
        case .fourthHr: return "fourth hr"
        case .genericSCIMV20: return "generic scim v2.0"
        case .gsuiteDirectory: return "gsuite directory"
        case .hibob: return "hibob"
        case .sailpointSCIMV20: return "sailpoint scim v2.0"
        case .jumpCloudSCIMV20: return "jump cloud scim v2.0"
        case .oktaSCIMV20: return "okta scim v2.0"
        case .oneloginSCIMV20: return "onelogin scim v2.0"
        case .peopleHr: return "people hr"
        case .personio: return "personio"
        case .pingfederateSCIMV20: return "pingfederate scim v2.0"
        case .ripplingSCIMV20: return "rippling scim v2.0"
        case .s3: return "s3"
        case .sftp: return "sftp"
        case .sftpWorkday: return "sftp workday"
        case .workday: return "workday"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [DirectoryType] = [
        .azureSCIMV20,
        .bamboohr,
        .breatheHr,
        .cezanneHr,
        .cyberarkSCIMV20,
        .fourthHr,
        .genericSCIMV20,
        .gsuiteDirectory,
        .hibob,
        .sailpointSCIMV20,
        .jumpCloudSCIMV20,
        .oktaSCIMV20,
        .oneloginSCIMV20,
        .peopleHr,
        .personio,
        .pingfederateSCIMV20,
        .ripplingSCIMV20,
        .s3,
        .sftp,
        .sftpWorkday,
        .workday,
    ]
}
