// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid DsyncActivatedDataState values.
public enum DsyncActivatedDataState: RawRepresentable, Codable, Sendable, Hashable {
    case active
    case validating
    case invalidCredentials
    case inactive
    case deleting
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "active": self = .active
        case "validating": self = .validating
        case "invalid_credentials": self = .invalidCredentials
        case "inactive": self = .inactive
        case "deleting": self = .deleting
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .active: return "active"
        case .validating: return "validating"
        case .invalidCredentials: return "invalid_credentials"
        case .inactive: return "inactive"
        case .deleting: return "deleting"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [DsyncActivatedDataState] = [
        .active,
        .validating,
        .invalidCredentials,
        .inactive,
        .deleting,
    ]
}
