// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid FlagUpdatedContextActorSource values.
public enum FlagUpdatedContextActorSource: RawRepresentable, Codable, Sendable, Hashable {
    case api
    case dashboard
    case adminPortal
    case system
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "api": self = .api
        case "dashboard": self = .dashboard
        case "admin_portal": self = .adminPortal
        case "system": self = .system
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .api: return "api"
        case .dashboard: return "dashboard"
        case .adminPortal: return "admin_portal"
        case .system: return "system"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [FlagUpdatedContextActorSource] = [.api, .dashboard, .adminPortal, .system]
}
