// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid GenerateLinkIntent values.
public enum GenerateLinkIntent: RawRepresentable, Codable, Sendable, Hashable {
    case sso
    case dsync
    case auditLogs
    case logStreams
    case domainVerification
    case certificateRenewal
    case bringYourOwnKey
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "sso": self = .sso
        case "dsync": self = .dsync
        case "audit_logs": self = .auditLogs
        case "log_streams": self = .logStreams
        case "domain_verification": self = .domainVerification
        case "certificate_renewal": self = .certificateRenewal
        case "bring_your_own_key": self = .bringYourOwnKey
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .sso: return "sso"
        case .dsync: return "dsync"
        case .auditLogs: return "audit_logs"
        case .logStreams: return "log_streams"
        case .domainVerification: return "domain_verification"
        case .certificateRenewal: return "certificate_renewal"
        case .bringYourOwnKey: return "bring_your_own_key"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [GenerateLinkIntent] = [.sso, .dsync, .auditLogs, .logStreams, .domainVerification, .certificateRenewal, .bringYourOwnKey]
}
