// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid InvitationResentDataState values.
public enum InvitationResentDataState: RawRepresentable, Codable, Sendable, Hashable {
    case pending
    case accepted
    case expired
    case revoked
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "pending": self = .pending
        case "accepted": self = .accepted
        case "expired": self = .expired
        case "revoked": self = .revoked
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .pending: return "pending"
        case .accepted: return "accepted"
        case .expired: return "expired"
        case .revoked: return "revoked"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [InvitationResentDataState] = [
        .pending,
        .accepted,
        .expired,
        .revoked,
    ]
}
