// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid OrganizationDomainVerificationStrategy values.
public enum OrganizationDomainVerificationStrategy: RawRepresentable, Codable, Sendable, Hashable {
    case dns
    case manual
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "dns": self = .dns
        case "manual": self = .manual
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .dns: return "dns"
        case .manual: return "manual"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [OrganizationDomainVerificationStrategy] = [.dns, .manual]
}
