// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid PatchConnectionOidcOptionsTokenAuthenticationMethod values.
public enum PatchConnectionOidcOptionsTokenAuthenticationMethod: RawRepresentable, Codable,
    Sendable, Hashable
{
    case clientSecretPost
    case clientSecretBasic
    case privateKeyJWT
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "client_secret_post": self = .clientSecretPost
        case "client_secret_basic": self = .clientSecretBasic
        case "private_key_jwt": self = .privateKeyJWT
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .clientSecretPost: return "client_secret_post"
        case .clientSecretBasic: return "client_secret_basic"
        case .privateKeyJWT: return "private_key_jwt"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [PatchConnectionOidcOptionsTokenAuthenticationMethod] = [
        .clientSecretPost,
        .clientSecretBasic,
        .privateKeyJWT,
    ]
}
