// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid RadarStandaloneResponseBlocklistType values.
public enum RadarStandaloneResponseBlocklistType: RawRepresentable, Codable, Sendable, Hashable {
    case ipAddress
    case domain
    case email
    case device
    case userAgent
    case deviceFingerprint
    case country
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "ip_address": self = .ipAddress
        case "domain": self = .domain
        case "email": self = .email
        case "device": self = .device
        case "user_agent": self = .userAgent
        case "device_fingerprint": self = .deviceFingerprint
        case "country": self = .country
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .ipAddress: return "ip_address"
        case .domain: return "domain"
        case .email: return "email"
        case .device: return "device"
        case .userAgent: return "user_agent"
        case .deviceFingerprint: return "device_fingerprint"
        case .country: return "country"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [RadarStandaloneResponseBlocklistType] = [
        .ipAddress,
        .domain,
        .email,
        .device,
        .userAgent,
        .deviceFingerprint,
        .country,
    ]
}
