// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid RadarListAction values.
public enum RadarListAction: RawRepresentable, Codable, Sendable, Hashable {
    case block
    case allow
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "block": self = .block
        case "allow": self = .allow
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .block: return "block"
        case .allow: return "allow"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [RadarListAction] = [.block, .allow]
}
