// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid RoleType values.
public enum RoleType: RawRepresentable, Codable, Sendable, Hashable {
    case environmentRole
    case organizationRole
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "EnvironmentRole": self = .environmentRole
        case "OrganizationRole": self = .organizationRole
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .environmentRole: return "EnvironmentRole"
        case .organizationRole: return "OrganizationRole"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [RoleType] = [.environmentRole, .organizationRole]
}
