// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid SessionRevokedDataStatus values.
public enum SessionRevokedDataStatus: RawRepresentable, Codable, Sendable, Hashable {
    case active
    case expired
    case revoked
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "active": self = .active
        case "expired": self = .expired
        case "revoked": self = .revoked
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .active: return "active"
        case .expired: return "expired"
        case .revoked: return "revoked"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [SessionRevokedDataStatus] = [.active, .expired, .revoked]
}
