// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid UpdateUserPasswordSaltPosition values.
public enum UpdateUserPasswordSaltPosition: RawRepresentable, Codable, Sendable, Hashable {
    case prefix
    case suffix
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "prefix": self = .prefix
        case "suffix": self = .suffix
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .prefix: return "prefix"
        case .suffix: return "suffix"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [UpdateUserPasswordSaltPosition] = [.prefix, .suffix]
}
