// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid UserIdentitiesGetItemProvider values.
public enum UserIdentitiesGetItemProvider: RawRepresentable, Codable, Sendable, Hashable {
    case appleOAuth
    case bitbucketOAuth
    case discordOAuth
    case githubOAuth
    case gitLabOAuth
    case googleOAuth
    case intuitOAuth
    case linkedInOAuth
    case microsoftOAuth
    case salesforceOAuth
    case slackOAuth
    case vercelMarketplaceOAuth
    case vercelOAuth
    case xeroOAuth
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "AppleOAuth": self = .appleOAuth
        case "BitbucketOAuth": self = .bitbucketOAuth
        case "DiscordOAuth": self = .discordOAuth
        case "GithubOAuth": self = .githubOAuth
        case "GitLabOAuth": self = .gitLabOAuth
        case "GoogleOAuth": self = .googleOAuth
        case "IntuitOAuth": self = .intuitOAuth
        case "LinkedInOAuth": self = .linkedInOAuth
        case "MicrosoftOAuth": self = .microsoftOAuth
        case "SalesforceOAuth": self = .salesforceOAuth
        case "SlackOAuth": self = .slackOAuth
        case "VercelMarketplaceOAuth": self = .vercelMarketplaceOAuth
        case "VercelOAuth": self = .vercelOAuth
        case "XeroOAuth": self = .xeroOAuth
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .appleOAuth: return "AppleOAuth"
        case .bitbucketOAuth: return "BitbucketOAuth"
        case .discordOAuth: return "DiscordOAuth"
        case .githubOAuth: return "GithubOAuth"
        case .gitLabOAuth: return "GitLabOAuth"
        case .googleOAuth: return "GoogleOAuth"
        case .intuitOAuth: return "IntuitOAuth"
        case .linkedInOAuth: return "LinkedInOAuth"
        case .microsoftOAuth: return "MicrosoftOAuth"
        case .salesforceOAuth: return "SalesforceOAuth"
        case .slackOAuth: return "SlackOAuth"
        case .vercelMarketplaceOAuth: return "VercelMarketplaceOAuth"
        case .vercelOAuth: return "VercelOAuth"
        case .xeroOAuth: return "XeroOAuth"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [UserIdentitiesGetItemProvider] = [
        .appleOAuth,
        .bitbucketOAuth,
        .discordOAuth,
        .githubOAuth,
        .gitLabOAuth,
        .googleOAuth,
        .intuitOAuth,
        .linkedInOAuth,
        .microsoftOAuth,
        .salesforceOAuth,
        .slackOAuth,
        .vercelMarketplaceOAuth,
        .vercelOAuth,
        .xeroOAuth,
    ]
}
