// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid UserRoleAssignmentSourceType values.
public enum UserRoleAssignmentSourceType: RawRepresentable, Codable, Sendable, Hashable {
    case direct
    case group
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "direct": self = .direct
        case "group": self = .group
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .direct: return "direct"
        case .group: return "group"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [UserRoleAssignmentSourceType] = [.direct, .group]
}
