// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid VaultOrder values.
public enum VaultOrder: RawRepresentable, Codable, Sendable, Hashable {
    case asc
    case desc
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "asc": self = .asc
        case "desc": self = .desc
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .asc: return "asc"
        case .desc: return "desc"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [VaultOrder] = [.asc, .desc]
}
