name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Swift build
        run: swift build

      - name: Swift test
        run: swift test

  build-ios:
    name: Build (iOS ${{ matrix.ios-version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ios-version: ['16.0', '17.0']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Swift build
        run: swift build --sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)" --triple arm64-apple-ios${{ matrix.ios-version }}-simulator
