name: Lint

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  standard:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run SwiftFormat
        run: ./script/lint
